# Evaluation

In [1]:
!huggingface-cli logout

Successfully logged out from all access tokens.

In [2]:
from huggingface_hub import notebook_login
access_token = "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" # only reading permit

notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

## File preparation to simulate final situation

Es wird eine Inputdatei für jede Task zum Testen generiert, sowie eine Golddatei pro Task gegen die die Ergebnisse verglichen werden können.

In [24]:
def clean_comments(data,column):
    data[column] = data[column].fillna(' ') # NaN Leerzeichen String ersetzen
    data[column] = data[column].apply(lambda x: ' ' if str(x).strip() == '' else x)
    return data

In [25]:
# adds the column "id" with  "document" + "_" + "comment_id"
def make_id_column(dataframe):
    dataframe["id"] = dataframe.apply(lambda x: x["document"] + "_" + str(x["comment_id"]), axis=1)
    return dataframe

In [26]:
import pandas as pd
import os
import csv

#path = ""
mode = "test" # "train" 
#path = "Input/Data/" + mode + "/"
path = "Input/Data/" + mode + "/"
submission_path = "Input/Data/submission/"
comment = pd.read_csv(path + "comments_extended.csv").reset_index(drop=True)
comment = clean_comments(comment,"comment")
comment = clean_comments(comment,"translated")
comment = clean_comments(comment,"spelling_corrected")
comment = make_id_column(comment)

if mode == "train":
    data1 = pd.read_json(path + "test_task1.json").reset_index(drop=True)
    data2 = pd.read_json(path + "test_task2.json").reset_index(drop=True)
    task1 = pd.read_csv(path + "task1.csv").reset_index(drop=True)
    task2 = pd.read_csv(path + "task2.csv").reset_index(drop=True)
    test_indices_task1 = [(x,y) for x,y in zip(data1["document"],data1["comment_id"])] # indices of our test set data
    test_data_task1 = comment[comment.set_index(["document", "comment_id"]).index.isin(test_indices_task1)].copy().reset_index(drop=True)
    gold_data_task1 = task1[task1.set_index(["document", "comment_id"]).index.isin(test_indices_task1)].copy().reset_index(drop=True)
    gold_data_task1.to_csv(path + "gold_data_task1.csv", index=False, quoting=csv.QUOTE_ALL)

    test_indices_task2 = [(x,y) for x,y in zip(data2["document"],data2["comment_id"])] # indices of our test set data
    test_data_task2 = comment[comment.set_index(["document", "comment_id"]).index.isin(test_indices_task2)].copy().reset_index(drop=True)
    gold_data_task2 = task2[task2.set_index(["document", "comment_id"]).index.isin(test_indices_task2)].copy().reset_index(drop=True)
    gold_data_task2.to_csv(path + "gold_data_task2.csv", index=False, quoting=csv.QUOTE_ALL)

if mode == "test": 
    test_data_task1 = comment.copy().reset_index(drop=True)

In [27]:
test_data_task1.head(3)

,document,comment_id,comment,translated,spelling_corrected,sentiment_orig,sentiment_spelling_corrected,sentiment_translated,id
0,NDY-004,1,Lol i love lochis,Lol i love lochis,LOL I love lochis!,0.0,0.0,0.65,NDY-004_1
1,NDY-004,2,ihr singt voll gut :),you sing very well :),Ihr singt voll gut -).,1.0,1.0,0.35,NDY-004_2
2,NDY-004,3,Junge fick dich,Boy fuck you,Junge fick dich.,0.0,0.0,-0.40,NDY-004_3

In [28]:
test_data_task1["spelling_corrected"].isna().sum(), test_data_task1["translated"].isna().sum(), test_data_task1["comment"].isna().sum()

(0, 0, 0)

## Official evaluation script

In [29]:
!#pip install multiset

Der Befehl "#pip" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

In [30]:
import pandas as pd
from sklearn.metrics import precision_recall_fscore_support
from multiset import *

# Labels for the fine grained classification
ALL_LABELS = ["affection declaration","agreement","ambiguous",
              "compliment","encouragement","gratitude","group membership",
              "implicit","positive feedback","sympathy"]

# TASK 1
def binary_eval(file_gold, file_pred):

    test_g = pd.read_csv(file_gold)
    test_p = pd.read_csv(file_pred)

    (bin_prec, bin_rec, bin_f, bin_supp) = precision_recall_fscore_support(test_g.flausch, test_p.flausch, pos_label="yes", average='binary')

    print("TASK 1: BINARY CLASSIFICATION",
          "\n=============================",
          "\nPrecision:\t %.4f" % bin_prec,
          "\nRecall:\t\t %.4f" % bin_rec,
          "\nF-score:\t %.4f" % bin_f)

    return((bin_prec, bin_rec, bin_f))


def fine_grained_flausch_by_label(file_gold, file_pred):

    # read files
    gold = pd.read_csv(file_gold)
    gold['cid']= gold['document']+"_"+gold['comment_id'].apply(str)
    predicted = pd.read_csv(file_pred)
    predicted['cid']= predicted['document']+"_"+predicted['comment_id'].apply(str)


    # annotation sets (predicted)
    pred_spans = Multiset()
    pred_spans_loose = Multiset()
    pred_types = Multiset()

    # annotation sets (gold)
    gold_spans = Multiset()
    gold_spans_loose = Multiset()
    gold_types = Multiset()

    for row in predicted.itertuples(index=False):
        pred_spans.add((row.cid,row.type,row.start,row.end))
        pred_spans_loose.add((row.cid,row.start,row.end))
        pred_types.add((row.cid,row.type))
    for row in gold.itertuples(index=False):
        gold_spans.add((row.cid,row.type,row.start,row.end))
        gold_spans_loose.add((row.cid,row.start,row.end))
        gold_types.add((row.cid,row.type))

    # precision = true_pos / true_pos + false_pos
    # recall = true_pos / true_pos + false_neg
    # f_1 = 2 * prec * rec / (prec + rec)

    results = {'TOTAL': {'STRICT': {},'SPANS': {},'TYPES': {}}}
    # label-wise evaluation (only for strict and type)
    for label in ALL_LABELS:
        results[label] = {'STRICT': {},'TYPES': {}}
        gold_spans_x = set(filter(lambda x: x[1].__eq__(label), gold_spans))
        pred_spans_x = set(filter(lambda x: x[1].__eq__(label), pred_spans))
        gold_types_x = set(filter(lambda x: x[1].__eq__(label), gold_types))
        pred_types_x = set(filter(lambda x: x[1].__eq__(label), pred_types))

        # strict: spans + type must match
        ### NOTE: x and y / x returns 0 if x = 0 and y/x otherwise (test for zero division)
        strict_p = float(len(pred_spans_x)) and float( len(gold_spans_x.intersection(pred_spans_x))) / len(pred_spans_x)
        strict_r = float(len(gold_spans_x)) and float( len(gold_spans_x.intersection(pred_spans_x))) / len(gold_spans_x)
        strict_f = (strict_p + strict_r) and 2 * strict_p * strict_r / (strict_p + strict_r)
        results[label]['STRICT']['prec'] = strict_p
        results[label]['STRICT']['rec'] = strict_r
        results[label]['STRICT']['f1'] = strict_f

        # detection mode: only types must match (per post)
        types_p = float(len(pred_types_x)) and float( len(gold_types_x.intersection(pred_types_x))) / len(pred_types_x)
        types_r = float(len(gold_types_x)) and float( len(gold_types_x.intersection(pred_types_x))) / len(gold_types_x)
        types_f = (types_p + types_r) and 2 * types_p * types_r / (types_p + types_r)
        results[label]['TYPES']['prec'] = types_p
        results[label]['TYPES']['rec'] = types_r
        results[label]['TYPES']['f1'] = types_f

    # Overall evaluation
    # strict: spans + type must match
    strict_p = float(len(pred_spans)) and float( len(gold_spans.intersection(pred_spans))) / len(pred_spans)
    strict_r = float(len(gold_spans)) and float( len(gold_spans.intersection(pred_spans))) / len(gold_spans)
    strict_f = (strict_p + strict_r) and 2 * strict_p * strict_r / (strict_p + strict_r)
    results['TOTAL']['STRICT']['prec'] = strict_p
    results['TOTAL']['STRICT']['rec'] = strict_r
    results['TOTAL']['STRICT']['f1'] = strict_f

    # spans: spans must match
    spans_p = float(len(pred_spans_loose)) and float( len(gold_spans_loose.intersection(pred_spans_loose))) / len(pred_spans_loose)
    spans_r = float(len(gold_spans_loose)) and float( len(gold_spans_loose.intersection(pred_spans_loose))) / len(gold_spans_loose)
    spans_f = (spans_p + spans_r) and 2 * spans_p * spans_r / (spans_p + spans_r)
    results['TOTAL']['SPANS']['prec'] = spans_p
    results['TOTAL']['SPANS']['rec'] = spans_r
    results['TOTAL']['SPANS']['f1'] = spans_f

    # detection mode: only types must match (per post)
    types_p = float(len(pred_types)) and float( len(gold_types.intersection(pred_types))) / len(pred_types)
    types_r = float(len(gold_types)) and float( len(gold_types.intersection(pred_types))) / len(gold_types)
    types_f = (types_p + types_r) and 2 * types_p * types_r / (types_p + types_r)
    results['TOTAL']['TYPES']['prec'] = types_p
    results['TOTAL']['TYPES']['rec'] = types_r
    results['TOTAL']['TYPES']['f1'] = types_f

    print("STRICT:\n ",strict_p,strict_r,strict_f)
    print("SPANS:\n ",spans_p,spans_r,spans_f)
    print("TYPES:\n ",types_p,types_r,types_f)
    return(results)

## Make submission file function

In [31]:
import csv
submission_path = "Input/Data/submission/"

def make_submission_task1(data, name):
    submission = data[["document","comment_id","flausch"]]
    for f in submission["flausch"]:
        if (f != "yes" and f != "no"):
            raise Exception("flausch prediction missing")
    submission.to_csv(submission_path + name + ".csv", index=False, quoting=csv.QUOTE_ALL)

In [32]:
def make_submission_task2(data, name):
    submission = data[["document","comment_id","type","start","end"]]
    for f in submission["start"]:
        if not type(f) is int:
            raise Exception("start prediction missing")
    for f in submission["end"]:
        if not type(f) is int:
            raise Exception("end prediction missing")
    submission.to_csv(submission_path + name + ".csv", index=False, quoting=csv.QUOTE_ALL)

## Task 1

#### BERT model gBert-large: binary classifier: yes/no flausch

In [33]:
# prediction with BERT model
from transformers import pipeline

checkpoint = "Wiebke/results_flausch_classification_"
# German models gBERT-large and bert-base-german-cased and multilingual model roberta-large
name =  "roberta-large"# "gbert-large" #"bert-base-german-cased" #
column = "translated" #"spelling_corrected" #  "comment" #
pipe = pipeline("text-classification", model= checkpoint + name + "_" + column, token=access_token)
tokenizer_kwargs = {'padding':True,'truncation':True,'max_length':512}

pipe(["testen wir doch mal was passiert", "das habt ihr großartig gmacht"], **tokenizer_kwargs)

Device set to use cpu

[{'label': 'no', 'score': 0.9978132247924805},
 {'label': 'yes', 'score': 0.9915341734886169}]

In [34]:
from datasets import Dataset

test_task1_dataset = Dataset.from_pandas(test_data_task1)
test_task1_dataset

Dataset({
    features: ['document', 'comment_id', 'comment', 'translated', 'spelling_corrected', 'sentiment_orig', 'sentiment_spelling_corrected', 'sentiment_translated', 'id'],
    num_rows: 9229
})

In [35]:
def apply_task1_pipeline(batch,pipeline,column):
    texts = batch[column]
    results_for_batch = pipeline(texts, **tokenizer_kwargs)
    predictions = []
    top_scores = [] # List to store the scores of the top prediction

    for top_pred_item in results_for_batch:
        # top_pred_item ist ein Dictionary
        # Beispiel: {'label': 'POSITIVE', 'score': 0.99}
        predictions.append(top_pred_item['label'])
        top_scores.append(top_pred_item['score'])

    # Return a dictionary with the new columns, matching the batch size
    return {'prediction': predictions, 'score': top_scores}

In [36]:
# for our test set 12 minutes on local machine on colab ~ 1 minute
prediction_dataset = test_task1_dataset.map(
    apply_task1_pipeline,
    batched=True,
    batch_size=16,
    num_proc=1,
    fn_kwargs={"pipeline": pipe, "column": column}
)

Map:   0%|          | 0/9229 [00:00<?, ? examples/s]

KeyboardInterrupt:

In [ ]:
# features.csv file is updated with name + "_yes_" + column column for scores for "yes"
df = pd.DataFrame(prediction_dataset).reset_index(drop=True)
df.loc[df["prediction"] == "no", "score"] = 1-df["score"]
# if path + features.csv does not exist, it will be created
if not os.path.exists(path + "features.csv"):
    features = test_data_task1[["id","document","comment_id"]].copy().reset_index(drop=True)
else:
    features = pd.read_csv(path + "features.csv").reset_index(drop=True)
features[name + "_yes_" + column] =  float('nan')
df["score"] = df["score"].astype(float)

score_dict = dict(zip(df["id"], df["score"]))

features[name + "_yes_" + column] = features["id"].map(score_dict)

features = features.drop(columns=[x for x in features.columns if x.startswith("Unnamed")])

features.to_csv(path + "features.csv")

In [ ]:
features.columns

Index(['id', 'set', 'gbert-large_yes_comment',
       'bert-base-german-cased_yes_comment',
       'bert-base-german-cased_yes_spelling_corrected',
       'gbert-large_yes_spelling_corrected', 'roberta-large_yes_translated'],
      dtype='object')

In [45]:
submission = pd.DataFrame(prediction_dataset)
submission["flausch"] = submission["prediction"]
submission_path = "" # only on colab
make_submission_task1(submission,"test_submission_task1_" + name + "_" + column)

In [46]:
file_gold = path + "gold_data_task1.csv"
file_pred = submission_path + "test_submission_task1_"  + name  + "_" + column + ".csv"
print("Evaluation for configuration", name, column)
binary_eval(file_gold, file_pred)

Evaluation for configuration roberta-large translated
TASK 1: BINARY CLASSIFICATION
=============================
Precision:	 0.8853
Recall:		 0.8649
F-score:	 0.8750

(0.8852941176470588, 0.8649425287356322, 0.875)

### Compare BERT classification models

In [157]:
features = pd.read_csv(path + "features.csv")

german_models = ["gbert-large", "bert-base-german-cased"]
english_models = ["roberta-large"]
german_columns = ["comment", "spelling_corrected"]
english_columns = ["translated"]
testdata = features[features["set"]=="test"].reset_index(drop=True)

gold = pd.read_csv(path + "gold_data_task1.csv") 
gold = make_id_column(gold)
gold = gold[["id", "flausch"]]
testdata = testdata.merge(gold, on="id")

test = testdata.copy()

cnames = []
for m in german_models:
    for c in german_columns:
        cname = m + "_yes_" + c
        cnames.append(cname)

for m in english_models:
    for c in english_columns:
        cname = m + "_yes_" + c
        cnames.append(cname)

for c in cnames:
    test[c] = test[c].apply(lambda x: "yes" if x > 0.5 else "no")

test.head(3)

,Unnamed: 0,id,set,gbert-large_yes_comment,bert-base-german-cased_yes_comment,bert-base-german-cased_yes_spelling_corrected,gbert-large_yes_spelling_corrected,roberta-large_yes_translated,flausch
0,4,NDY-003_5,test,yes,yes,yes,yes,yes,yes
1,13,NDY-003_14,test,no,no,no,no,no,no
2,40,NDY-003_41,test,yes,yes,yes,yes,no,yes

In [193]:
import numpy as np
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score, accuracy_score
for c in cnames:
    gold = test["flausch"]
    pred = test[c]
    print()
    print(c)
    print("weighted F1 score:", f1_score(gold,pred,average="weighted"))
    print("accuracy:", accuracy_score(gold,pred))
    print(classification_report(gold,pred))

gbert-large_yes_comment
weighted F1 score: 0.9456839415000671
accuracy: 0.9452239611440907
              precision    recall  f1-score   support

          no       0.97      0.95      0.96      2662
         yes       0.88      0.93      0.91      1044

    accuracy                           0.95      3706
   macro avg       0.93      0.94      0.93      3706
weighted avg       0.95      0.95      0.95      3706


gbert-large_yes_spelling_corrected
weighted F1 score: 0.9411003608844272
accuracy: 0.9409066378845116
              precision    recall  f1-score   support

          no       0.96      0.95      0.96      2662
         yes       0.89      0.91      0.90      1044

    accuracy                           0.94      3706
   macro avg       0.92      0.93      0.93      3706
weighted avg       0.94      0.94      0.94      3706


bert-base-german-cased_yes_comment
weighted F1 score: 0.9349608447726743
accuracy: 0.9349703184025904
              precision    recall  f1-score   support

          no       0.95      0.95      0.95      2662
         yes       0.88      0.88      0.88      1044

    accuracy                           0.93      3706
   macro avg       0.92      0.92      0.92      3706
weighted avg       0.93      0.93      0.93      3706


bert-base-german-cased_yes_spelling_corrected
weighted F1 score: 0.9325221513614445
accuracy: 0.9325418240690772
              precision    recall  f1-score   support

          no       0.95      0.95      0.95      2662
         yes       0.88      0.88      0.88      1044

    accuracy                           0.93      3706
   macro avg       0.92      0.92      0.92      3706
weighted avg       0.93      0.93      0.93      3706


roberta-large_yes_translated
weighted F1 score: 0.9301346216953567
accuracy: 0.9303831624392876
              precision    recall  f1-score   support

          no       0.95      0.96      0.95      2662
         yes       0.89      0.86      0.87      1044

    accuracy                           0.93      3706
   macro avg       0.92      0.91      0.91      3706
weighted avg       0.93      0.93      0.93      3706

In [159]:
id_false = test[test["gbert-large_yes_comment"] != test["flausch"]]["id"]
false = testdata[testdata["id"].isin(id_false)]
false

,Unnamed: 0,id,set,gbert-large_yes_comment,bert-base-german-cased_yes_comment,bert-base-german-cased_yes_spelling_corrected,gbert-large_yes_spelling_corrected,roberta-large_yes_translated,flausch
21,261,NDY-003_262,test,0.991680,0.989212,0.993828,0.991255,0.995281,no
22,263,NDY-003_264,test,0.990066,0.158031,0.317640,0.972652,0.994509,no
30,314,NDY-003_315,test,0.940336,0.487242,0.991803,0.989425,0.993041,no
87,943,NDY-003_944,test,0.970248,0.003784,0.004983,0.991856,0.992910,no
92,977,NDY-003_978,test,0.968321,0.001037,0.008553,0.532543,0.954395,no
...,...,...,...,...,...,...,...,...,...
3567,35681,NDY-252_132,test,0.716943,0.005428,0.113768,0.922664,0.022369,no
3615,36236,NDY-252_687,test,0.685843,0.932554,0.377381,0.032994,0.989608,no
3659,36639,NDY-274_91,test,0.943479,0.079387,0.151630,0.020367,0.990125,no
3679,36811,NDY-274_263,test,0.042193,0.000325,0.001814,0.013124,0.003413,yes
3691,36887,NDY-285_34,test,0.964197,0.006723,0.007373,0.816801,0.012434,no

In [191]:
### train a metaclassifier

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X = testdata[cnames]
y = testdata["flausch"]

X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2, random_state=42)



model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nRandom Forest")
print("F1 score weighted:",f1_score(y_test, y_pred,average="weighted"))
print("accuracy:",accuracy_score(y_test, y_pred))

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nDecision Tree")
print("F1 score weighted:",f1_score(y_test, y_pred,average="weighted"))
print("accuracy:",accuracy_score(y_test, y_pred))



model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nLogistic Regression")
print("F1 score weighted:",f1_score(y_test, y_pred,average="weighted"))
print("accuracy:",accuracy_score(y_test, y_pred))
print("coefficient    ", "configuration")
for i in range(len(X_test.columns)):
    print(model.coef_[0][i], " ", X_test.columns[i])


print(classification_report(y_test, y_pred))

Random Forest
F1 score weighted: 0.9538939248821557
accuracy: 0.954177897574124

Decision Tree
F1 score weighted: 0.9205443183562734
accuracy: 0.9204851752021563

Logistic Regression
F1 score weighted: 0.9593181690136667
accuracy: 0.9595687331536388
coefficient     configuration
2.6539389962917794   gbert-large_yes_comment
1.3578417180676143   gbert-large_yes_spelling_corrected
0.8748385286776595   bert-base-german-cased_yes_comment
1.0086257907005658   bert-base-german-cased_yes_spelling_corrected
0.8701515629176588   roberta-large_yes_translated
              precision    recall  f1-score   support

          no       0.97      0.98      0.97       536
         yes       0.94      0.91      0.93       206

    accuracy                           0.96       742
   macro avg       0.95      0.94      0.95       742
weighted avg       0.96      0.96      0.96       742

## Task 2

BERT model gBERT-large: Token classification BIO scheme

In [ ]:
from transformers import pipeline
checkpoint = "Wiebke/flausch_span_gbert-large"
pipe = pipeline("token-classification", model=checkpoint)
pipe("das habt ihr großartig gmacht. Macht weiter so. Nächsten Monat wird es warm. Team Sommer!!!!")

Device set to use cpu

[{'entity': 'B-compliment',
  'score': 0.9641225,
  'index': 1,
  'word': 'das',
  'start': 0,
  'end': 3},
 {'entity': 'I-compliment',
  'score': 0.99075025,
  'index': 2,
  'word': 'habt',
  'start': 4,
  'end': 8},
 {'entity': 'I-compliment',
  'score': 0.9893371,
  'index': 3,
  'word': 'ihr',
  'start': 9,
  'end': 12},
 {'entity': 'I-compliment',
  'score': 0.9908408,
  'index': 4,
  'word': 'großartig',
  'start': 13,
  'end': 22},
 {'entity': 'I-compliment',
  'score': 0.987295,
  'index': 5,
  'word': 'g',
  'start': 23,
  'end': 24},
 {'entity': 'I-compliment',
  'score': 0.990928,
  'index': 6,
  'word': '##macht',
  'start': 24,
  'end': 29},
 {'entity': 'B-encouragement',
  'score': 0.9910272,
  'index': 8,
  'word': 'Macht',
  'start': 31,
  'end': 36},
 {'entity': 'I-encouragement',
  'score': 0.9940864,
  'index': 9,
  'word': 'weiter',
  'start': 37,
  'end': 43},
 {'entity': 'I-encouragement',
  'score': 0.9958341,
  'index': 10,
  'word': 'so',
  'start': 44,
  'end': 46}]

In [ ]:
texts = ["Hunde sind Säugetiere", "großen Dank", "das habt ihr großartig gmacht. Macht weiter so. Nächsten Monat wird es warm. Team Sommer!!!!"]
pipe(texts)

[[{'entity': 'B-affection declaration',
   'score': 0.3012683,
   'index': 1,
   'word': 'Hunde',
   'start': 0,
   'end': 5}],
 [{'entity': 'B-gratitude',
   'score': 0.87086165,
   'index': 1,
   'word': 'großen',
   'start': 0,
   'end': 6},
  {'entity': 'I-gratitude',
   'score': 0.78514546,
   'index': 2,
   'word': 'Dank',
   'start': 7,
   'end': 11}],
 [{'entity': 'B-compliment',
   'score': 0.9641225,
   'index': 1,
   'word': 'das',
   'start': 0,
   'end': 3},
  {'entity': 'I-compliment',
   'score': 0.99075025,
   'index': 2,
   'word': 'habt',
   'start': 4,
   'end': 8},
  {'entity': 'I-compliment',
   'score': 0.9893371,
   'index': 3,
   'word': 'ihr',
   'start': 9,
   'end': 12},
  {'entity': 'I-compliment',
   'score': 0.9908408,
   'index': 4,
   'word': 'großartig',
   'start': 13,
   'end': 22},
  {'entity': 'I-compliment',
   'score': 0.987295,
   'index': 5,
   'word': 'g',
   'start': 23,
   'end': 24},
  {'entity': 'I-compliment',
   'score': 0.990928,
   'index': 6,
   'word': '##macht',
   'start': 24,
   'end': 29},
  {'entity': 'B-encouragement',
   'score': 0.9910272,
   'index': 8,
   'word': 'Macht',
   'start': 31,
   'end': 36},
  {'entity': 'I-encouragement',
   'score': 0.9940864,
   'index': 9,
   'word': 'weiter',
   'start': 37,
   'end': 43},
  {'entity': 'I-encouragement',
   'score': 0.9958341,
   'index': 10,
   'word': 'so',
   'start': 44,
   'end': 46}]]

In [ ]:
def apply_task2_pipeline(batch,pipeline,column):
    texts = batch[column]
    results_for_batch = pipeline(texts)

    types = []
    starts = []
    ends = []
    scores = []

    for single_text_result in results_for_batch:
        # single_text_result ist eine Liste von Dictionaries
        # Beispiel: [{'entity': 'B-gratitude', 'score': 0.87086165, 'index': 1,  'word': 'großen', 'start': 0,  'end': 6},
        #{'entity': 'I-gratitude','score': 0.78514546, 'index': 2,'word': 'Dank','start': 7,'end': 11}],
        type = []
        start = []
        end = []
        score = []
        for dic in single_text_result:
            type.append(dic['entity'])
            start.append(dic['start'])
            end.append(dic['end'])
            score.append(dic['score'])

        types.append(type)
        starts.append(start)
        ends.append(end)
        scores.append(score)

    # Return a dictionary with the new columns, matching the batch size
    return {'types': types, 'starts': starts, 'ends': ends, 'scores': scores}

In [ ]:
from datasets import Dataset

test_task2_dataset = Dataset.from_pandas(test_data_task2)

In [ ]:
prediction_dataset = test_task2_dataset.map(
    apply_task2_pipeline,
    batched=True,
    batch_size=16,
    num_proc=1,
    fn_kwargs={"pipeline": pipe, "column": "comment"}
)

Map:   0%|          | 0/1044 [00:00<?, ? examples/s]

In [ ]:
def map_to_type(string):
    return string.split("-")[1]



# neuer Versuch
def merge_types(row):
    if len(row["types"]) == 0:
        return row
    current_t = map_to_type(row["types"][0])
    filter = [1]
    filter_end = [0]
    if len(row["types"]) > 1:
        for t in row["types"][1:]:
            if t == "I-" + current_t:
                filter.append(0)
                filter_end.append(0)
            else:
                filter_end[-1] = 2
                current_t = map_to_type(t)
                filter.append(1)
                filter_end.append(0)
        filter_end[-1] = 2
    filter_end[-1] = 2
    row["types"] = [row["types"][i] for i in range(len(filter)) if filter[i] == 1]
    row["starts"] = [row["starts"][i] for i in range(len(filter)) if filter[i] == 1]
    row["ends"] = [row["ends"][i] for i in range(len(filter_end)) if filter_end[i] == 2]
    if len(row["types"]) != len(row["starts"]):
        print("problem types-Länge ungleich starts-Länge")
    if len(row["types"]) != len(row["ends"]):
        print("problem types-Länge ungleich ends-Länge")
        print(filter)
        print(filter_end)
        print()
    return row

In [ ]:

def output_task2(df):
#    df["types"] = df["types"].apply(lambda x: list(map(map_to_type, x)))
    df = df.apply(merge_types, axis=1)
    output = []
    for i in range(df.shape[0]):
        types, starts, ends = df.loc[i][["types","starts","ends"]]
        if len(types) > 0:
            document, comment_id = df.loc[i][["document", "comment_id"]]
            for j in range(len(types)):
                output.append({"document": document,"comment_id": comment_id,
                               "type": map_to_type(types[j]), "start": starts[j],"end":ends[j]})
    return pd.DataFrame(output)

In [ ]:
df = pd.DataFrame(prediction_dataset)
out_task2 = output_task2(df)
make_submission_task2(out_task2, "test_submission_task2_gbert")

In [ ]:
out_task2.shape, gold_data_task2.shape

((1648, 5), (1517, 5))

In [ ]:
file_gold = path + "gold_data_task2.csv"
file_pred = submission_path + "test_submission_task2_gbert" + ".csv"
results = fine_grained_flausch_by_label(file_gold, file_pred)

typeList = gold_data_task2["type"].unique()
all = []
for t in typeList:
    print(t)
    print(pd.DataFrame(results[t]))
    print()

STRICT:
  0.6711165048543689 0.7290705339485827 0.6988941548183254
SPANS:
  0.7099514563106796 0.7712590639419907 0.7393364928909953
TYPES:
  0.8270631067961165 0.8984838497033619 0.8612954186413903
positive feedback
        STRICT     TYPES
prec  0.722093  0.941878
rec   0.763838  0.953243
f1    0.742379  0.947526

affection declaration
        STRICT     TYPES
prec  0.644128  0.879828
rec   0.718254  0.899123
f1    0.679174  0.889371

group membership
        STRICT     TYPES
prec  0.421053  0.875000
rec   0.380952  0.777778
f1    0.400000  0.823529

encouragement
        STRICT     TYPES
prec  0.635417  0.916667
rec   0.701149  0.927711
f1    0.666667  0.922156

compliment
        STRICT     TYPES
prec  0.612500  0.890688
rec   0.734082  0.928270
f1    0.667802  0.909091

ambiguous
        STRICT     TYPES
prec  0.454545  0.818182
rec   0.227273  0.409091
f1    0.303030  0.545455

implicit
        STRICT     TYPES
prec  0.363636  0.454545
rec   0.363636  0.454545
f1    0.363636  0.454545

sympathy
      STRICT     TYPES
prec     0.0  0.100000
rec      0.0  0.200000
f1       0.0  0.133333

agreement
      STRICT  TYPES
prec   0.625   0.75
rec    0.625   0.75
f1     0.625   0.75

gratitude
        STRICT     TYPES
prec  0.869565  1.000000
rec   0.869565  0.909091
f1    0.869565  0.952381

In [ ]:
dfa= out_task2
dfb =  gold_data_task2

# Finde die Zeilen in df2, die auch in df1 sind
# Ein 'merge' mit 'indicator=True' zeigt an, woher die Zeilen kommen
merged_dfb = dfb.merge(dfa, how='left', indicator=True)
merged_dfa = dfa.merge(dfb, how='left', indicator=True)


# Filtere nur die Zeilen, die NICHT in df1 vorkommen
# '_merge' == 'left_only' bedeutet, die Zeile war nur in df2
dfb_cleaned_all_cols = merged_dfb[merged_dfb['_merge'] == 'left_only'].drop(columns=['_merge'])
dfa_cleaned_all_cols = merged_dfa[merged_dfa['_merge'] == 'left_only'].drop(columns=['_merge'])

In [ ]:
dfa.shape, dfa_cleaned_all_cols.shape, dfb.shape, dfb_cleaned_all_cols.shape

((1648, 5), (542, 5), (1517, 5), (411, 5))

In [ ]:
dfa_cleaned_all_cols.loc[10:25]

   document  comment_id                   type  start  end
10  NDY-003          76  affection declaration    367  369
11  NDY-003          76       group membership    370  374
14  NDY-003          97               implicit      0   55
15  NDY-003          97          encouragement     56   67
16  NDY-003         117             compliment     69   73
19  NDY-003         145             compliment    194  198
20  NDY-003         145      positive feedback    199  207
21  NDY-003         145             compliment    208  215
22  NDY-003         145      positive feedback    216  251
23  NDY-003         145             compliment    252  265
24  NDY-003         166      positive feedback      0   15

In [ ]:
dfb_cleaned_all_cols.loc[10:25]

   document  comment_id                   type  start  end
12  NDY-003          97          encouragement      0   67
15  NDY-003         145      positive feedback    194  267
16  NDY-003         166  affection declaration      0   15
20  NDY-003         267             compliment      0   40
21  NDY-003         267      positive feedback     43   63

In [ ]:
document = "NDY-003"
comment_id = 76

# get prediction_dataset and gold_data_task2 mit document and comment_id

filtered_rows_gold = gold_data_task2[(gold_data_task2['document'] == document) & (gold_data_task2['comment_id'] == comment_id)]
print(filtered_rows_gold)

filtered_rows_out = out_task2[(out_task2['document'] == document) & (out_task2['comment_id'] == comment_id)]

print()
print(filtered_rows_out)

   document  comment_id                   type  start  end
68  NDY-003          76  affection declaration     24   59
69  NDY-003          76       group membership     60   86
70  NDY-003          76      positive feedback    135  173
71  NDY-003          76  affection declaration    176  204
72  NDY-003          76      positive feedback    209  248
73  NDY-003          76      positive feedback    251  286
74  NDY-003          76  affection declaration    342  353

   document  comment_id                   type  start  end
3   NDY-003          76  affection declaration     24   59
4   NDY-003          76       group membership     60   88
5   NDY-003          76      positive feedback    135  175
6   NDY-003          76  affection declaration    176  204
7   NDY-003          76      positive feedback    209  248
8   NDY-003          76  affection declaration    342  353
9   NDY-003          76       group membership    359  362
10  NDY-003          76  affection declaration    367  369
11  NDY-003          76       group membership    370  374

Beobachtung: eigene sind häufiger etwas zu lang.