# Evaluation

In [76]:
!huggingface-cli logout

Successfully logged out from all access tokens.

In [77]:
from huggingface_hub import notebook_login
access_token = "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" # only reading permit

notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [78]:
# mount google drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## File preparation to simulate final situation

Es wird eine Inputdatei für jede Task zum Testen generiert, sowie eine Golddatei pro Task gegen die die Ergebnisse verglichen werden können.

In [79]:
def clean_comments(data,column):
    data[column] = data[column].fillna(' ') # NaN Leerzeichen String ersetzen
    data[column] = data[column].apply(lambda x: ' ' if str(x).strip() == '' else x)
    return data

In [80]:
# adds the column "id" with  "document" + "_" + "comment_id"
def make_id_column(dataframe):
    dataframe["id"] = dataframe.apply(lambda x: x["document"] + "_" + str(x["comment_id"]), axis=1)
    return dataframe

In [81]:
import pandas as pd
import os
import csv
from urllib.request import urlopen

mode = "train"# "test" #
flausch_mode = "all" # ""

google_path = "Input/Data/"
#auskommentieren wenn lokal
google_path = "/content/drive/MyDrive/FlauschData/"

path = google_path + mode +"/"
submission_path = google_path + "submission/"


if mode == "train":
    comment = pd.read_csv(path + "comments_extended.csv").reset_index(drop=True)
    comment = clean_comments(comment,"comment")
    comment = clean_comments(comment,"translated")
    comment = clean_comments(comment,"spelling_corrected")
    comment = make_id_column(comment)

    data1 = pd.read_json(path + "test_task1.json").reset_index(drop=True)
    data2 = pd.read_json(path + "test_task2.json").reset_index(drop=True)
    task1 = pd.read_csv(path + "task1.csv").reset_index(drop=True)
    task2 = pd.read_csv(path + "task2.csv").reset_index(drop=True)
    test_indices_task1 = [(x,y) for x,y in zip(data1["document"],data1["comment_id"])] # indices of our test set data
    test_data_task1 = comment[comment.set_index(["document", "comment_id"]).index.isin(test_indices_task1)].copy().reset_index(drop=True)
    gold_data_task1 = task1[task1.set_index(["document", "comment_id"]).index.isin(test_indices_task1)].copy().reset_index(drop=True)
    gold_data_task1.to_csv(path + "gold_data_task1.csv", index=False, quoting=csv.QUOTE_ALL)

    test_indices_task2 = [(x,y) for x,y in zip(data2["document"],data2["comment_id"])] # indices of our test set data
    test_data_task2 = comment[comment.set_index(["document", "comment_id"]).index.isin(test_indices_task2)].copy().reset_index(drop=True)
    gold_data_task2 = task2[task2.set_index(["document", "comment_id"]).index.isin(test_indices_task2)].copy().reset_index(drop=True)
    gold_data_task2.to_csv(path + "gold_data_task2.csv", index=False, quoting=csv.QUOTE_ALL)

    if flausch_mode == "all":
      test_data_task2 = test_data_task1.copy().reset_index(drop=True)

if mode == "test":
    comment = pd.read_csv(path + "comments_extended.csv").reset_index(drop=True)
    comment = clean_comments(comment,"comment")
    comment = clean_comments(comment,"translated")
    comment = clean_comments(comment,"spelling_corrected")
    comment = make_id_column(comment)
    test_data_task1 = comment.reset_index(drop=True)
    test_data_task2 = comment.reset_index(drop=True)

In [82]:
test_data_task1["spelling_corrected"].isna().sum(), test_data_task1["translated"].isna().sum(), test_data_task1["comment"].isna().sum()

(np.int64(0), np.int64(0), np.int64(0))

In [83]:
test_data_task1.shape, test_data_task2.shape, comment.shape

((3706, 17), (3706, 17), (37057, 17))

## Official evaluation script

In [84]:
!pip install multiset

Requirement already satisfied: multiset in /usr/local/lib/python3.11/dist-packages (3.2.0)

In [186]:
import pandas as pd
from sklearn.metrics import precision_recall_fscore_support
from multiset import *

# Labels for the fine grained classification
ALL_LABELS = ["affection declaration","agreement","ambiguous",
              "compliment","encouragement","gratitude","group membership",
              "implicit","positive feedback","sympathy"]

# TASK 1
def binary_eval(file_gold, file_pred):

    test_g = pd.read_csv(file_gold)
    test_p = pd.read_csv(file_pred)

    (bin_prec, bin_rec, bin_f, bin_supp) = precision_recall_fscore_support(test_g.flausch, test_p.flausch, pos_label="yes", average='binary')

    print("TASK 1: BINARY CLASSIFICATION",
          "\n=============================",
          "\nPrecision:\t %.4f" % bin_prec,
          "\nRecall:\t\t %.4f" % bin_rec,
          "\nF-score:\t %.4f" % bin_f)

    return((bin_prec, bin_rec, bin_f))


def fine_grained_flausch_by_label(file_gold, file_pred):

    # read files
    gold = pd.read_csv(file_gold)
    gold['cid']= gold['document']+"_"+gold['comment_id'].apply(str)
    predicted = pd.read_csv(file_pred)
    predicted['cid']= predicted['document']+"_"+predicted['comment_id'].apply(str)


    # annotation sets (predicted)
    pred_spans = Multiset()
    pred_spans_loose = Multiset()
    pred_types = Multiset()

    # annotation sets (gold)
    gold_spans = Multiset()
    gold_spans_loose = Multiset()
    gold_types = Multiset()

    for row in predicted.itertuples(index=False):
        pred_spans.add((row.cid,row.type,row.start,row.end))
        pred_spans_loose.add((row.cid,row.start,row.end))
        pred_types.add((row.cid,row.type))
    for row in gold.itertuples(index=False):
        gold_spans.add((row.cid,row.type,row.start,row.end))
        gold_spans_loose.add((row.cid,row.start,row.end))
        gold_types.add((row.cid,row.type))

    # precision = true_pos / true_pos + false_pos
    # recall = true_pos / true_pos + false_neg
    # f_1 = 2 * prec * rec / (prec + rec)

    results = {'TOTAL': {'STRICT': {},'SPANS': {},'TYPES': {}}}
    # label-wise evaluation (only for strict and type)
    for label in ALL_LABELS:
        results[label] = {'STRICT': {},'TYPES': {}}
        gold_spans_x = set(filter(lambda x: x[1].__eq__(label), gold_spans))
        pred_spans_x = set(filter(lambda x: x[1].__eq__(label), pred_spans))
        gold_types_x = set(filter(lambda x: x[1].__eq__(label), gold_types))
        pred_types_x = set(filter(lambda x: x[1].__eq__(label), pred_types))

        # strict: spans + type must match
        ### NOTE: x and y / x returns 0 if x = 0 and y/x otherwise (test for zero division)
        strict_p = float(len(pred_spans_x)) and float( len(gold_spans_x.intersection(pred_spans_x))) / len(pred_spans_x)
        strict_r = float(len(gold_spans_x)) and float( len(gold_spans_x.intersection(pred_spans_x))) / len(gold_spans_x)
        strict_f = (strict_p + strict_r) and 2 * strict_p * strict_r / (strict_p + strict_r)
        results[label]['STRICT']['prec'] = strict_p
        results[label]['STRICT']['rec'] = strict_r
        results[label]['STRICT']['f1'] = strict_f

        # detection mode: only types must match (per post)
        types_p = float(len(pred_types_x)) and float( len(gold_types_x.intersection(pred_types_x))) / len(pred_types_x)
        types_r = float(len(gold_types_x)) and float( len(gold_types_x.intersection(pred_types_x))) / len(gold_types_x)
        types_f = (types_p + types_r) and 2 * types_p * types_r / (types_p + types_r)
        results[label]['TYPES']['prec'] = types_p
        results[label]['TYPES']['rec'] = types_r
        results[label]['TYPES']['f1'] = types_f

    # Overall evaluation
    # strict: spans + type must match
    strict_p = float(len(pred_spans)) and float( len(gold_spans.intersection(pred_spans))) / len(pred_spans)
    strict_r = float(len(gold_spans)) and float( len(gold_spans.intersection(pred_spans))) / len(gold_spans)
    strict_f = (strict_p + strict_r) and 2 * strict_p * strict_r / (strict_p + strict_r)
    results['TOTAL']['STRICT']['prec'] = strict_p
    results['TOTAL']['STRICT']['rec'] = strict_r
    results['TOTAL']['STRICT']['f1'] = strict_f

    # spans: spans must match
    spans_p = float(len(pred_spans_loose)) and float( len(gold_spans_loose.intersection(pred_spans_loose))) / len(pred_spans_loose)
    spans_r = float(len(gold_spans_loose)) and float( len(gold_spans_loose.intersection(pred_spans_loose))) / len(gold_spans_loose)
    spans_f = (spans_p + spans_r) and 2 * spans_p * spans_r / (spans_p + spans_r)
    results['TOTAL']['SPANS']['prec'] = spans_p
    results['TOTAL']['SPANS']['rec'] = spans_r
    results['TOTAL']['SPANS']['f1'] = spans_f

    # detection mode: only types must match (per post)
    types_p = float(len(pred_types)) and float( len(gold_types.intersection(pred_types))) / len(pred_types)
    types_r = float(len(gold_types)) and float( len(gold_types.intersection(pred_types))) / len(gold_types)
    types_f = (types_p + types_r) and 2 * types_p * types_r / (types_p + types_r)
    results['TOTAL']['TYPES']['prec'] = types_p
    results['TOTAL']['TYPES']['rec'] = types_r
    results['TOTAL']['TYPES']['f1'] = types_f

    print("STRICT:\n ",strict_p,strict_r,strict_f)
    print("SPANS:\n ",spans_p,spans_r,spans_f)
    print("TYPES:\n ",types_p,types_r,types_f)
    return(results)




def on_data_fine_grained_flausch_by_label(gold, predicted):

    gold['cid']= gold['document']+"_"+gold['comment_id'].apply(str)
    predicted['cid']= predicted['document']+"_"+predicted['comment_id'].apply(str)


    # annotation sets (predicted)
    pred_spans = Multiset()
    pred_spans_loose = Multiset()
    pred_types = Multiset()

    # annotation sets (gold)
    gold_spans = Multiset()
    gold_spans_loose = Multiset()
    gold_types = Multiset()

    for row in predicted.itertuples(index=False):
        pred_spans.add((row.cid,row.type,row.start,row.end))
        pred_spans_loose.add((row.cid,row.start,row.end))
        pred_types.add((row.cid,row.type))
    for row in gold.itertuples(index=False):
        gold_spans.add((row.cid,row.type,row.start,row.end))
        gold_spans_loose.add((row.cid,row.start,row.end))
        gold_types.add((row.cid,row.type))

    # precision = true_pos / true_pos + false_pos
    # recall = true_pos / true_pos + false_neg
    # f_1 = 2 * prec * rec / (prec + rec)

    results = {'TOTAL': {'STRICT': {},'SPANS': {},'TYPES': {}}}
    # label-wise evaluation (only for strict and type)
    for label in ALL_LABELS:
        results[label] = {'STRICT': {},'TYPES': {}}
        gold_spans_x = set(filter(lambda x: x[1].__eq__(label), gold_spans))
        pred_spans_x = set(filter(lambda x: x[1].__eq__(label), pred_spans))
        gold_types_x = set(filter(lambda x: x[1].__eq__(label), gold_types))
        pred_types_x = set(filter(lambda x: x[1].__eq__(label), pred_types))

        # strict: spans + type must match
        ### NOTE: x and y / x returns 0 if x = 0 and y/x otherwise (test for zero division)
        strict_p = float(len(pred_spans_x)) and float( len(gold_spans_x.intersection(pred_spans_x))) / len(pred_spans_x)
        strict_r = float(len(gold_spans_x)) and float( len(gold_spans_x.intersection(pred_spans_x))) / len(gold_spans_x)
        strict_f = (strict_p + strict_r) and 2 * strict_p * strict_r / (strict_p + strict_r)
        results[label]['STRICT']['prec'] = strict_p
        results[label]['STRICT']['rec'] = strict_r
        results[label]['STRICT']['f1'] = strict_f

        # detection mode: only types must match (per post)
        types_p = float(len(pred_types_x)) and float( len(gold_types_x.intersection(pred_types_x))) / len(pred_types_x)
        types_r = float(len(gold_types_x)) and float( len(gold_types_x.intersection(pred_types_x))) / len(gold_types_x)
        types_f = (types_p + types_r) and 2 * types_p * types_r / (types_p + types_r)
        results[label]['TYPES']['prec'] = types_p
        results[label]['TYPES']['rec'] = types_r
        results[label]['TYPES']['f1'] = types_f

    # Overall evaluation
    # strict: spans + type must match
    strict_p = float(len(pred_spans)) and float( len(gold_spans.intersection(pred_spans))) / len(pred_spans)
    strict_r = float(len(gold_spans)) and float( len(gold_spans.intersection(pred_spans))) / len(gold_spans)
    strict_f = (strict_p + strict_r) and 2 * strict_p * strict_r / (strict_p + strict_r)
    results['TOTAL']['STRICT']['prec'] = strict_p
    results['TOTAL']['STRICT']['rec'] = strict_r
    results['TOTAL']['STRICT']['f1'] = strict_f

    # spans: spans must match
    spans_p = float(len(pred_spans_loose)) and float( len(gold_spans_loose.intersection(pred_spans_loose))) / len(pred_spans_loose)
    spans_r = float(len(gold_spans_loose)) and float( len(gold_spans_loose.intersection(pred_spans_loose))) / len(gold_spans_loose)
    spans_f = (spans_p + spans_r) and 2 * spans_p * spans_r / (spans_p + spans_r)
    results['TOTAL']['SPANS']['prec'] = spans_p
    results['TOTAL']['SPANS']['rec'] = spans_r
    results['TOTAL']['SPANS']['f1'] = spans_f

    # detection mode: only types must match (per post)
    types_p = float(len(pred_types)) and float( len(gold_types.intersection(pred_types))) / len(pred_types)
    types_r = float(len(gold_types)) and float( len(gold_types.intersection(pred_types))) / len(gold_types)
    types_f = (types_p + types_r) and 2 * types_p * types_r / (types_p + types_r)
    results['TOTAL']['TYPES']['prec'] = types_p
    results['TOTAL']['TYPES']['rec'] = types_r
    results['TOTAL']['TYPES']['f1'] = types_f

    print("STRICT:\n ",strict_p,strict_r,strict_f)
    print("SPANS:\n ",spans_p,spans_r,spans_f)
    print("TYPES:\n ",types_p,types_r,types_f)
    return(results)






def on_data_flausch_spans(gold, predicted):

    gold['cid']= gold['document']+"_"+gold['comment_id'].apply(str)
    predicted['cid']= predicted['document']+"_"+predicted['comment_id'].apply(str)


    # annotation sets (predicted)
    pred_spans = Multiset()
    pred_spans_loose = Multiset()
    pred_types = Multiset()

    # annotation sets (gold)
    gold_spans = Multiset()
    gold_spans_loose = Multiset()
    gold_types = Multiset()

    for row in predicted.itertuples(index=False):
        pred_spans.add((row.cid,row.type,row.start,row.end))
        pred_spans_loose.add((row.cid,row.start,row.end))
        pred_types.add((row.cid,row.type))
    for row in gold.itertuples(index=False):
        gold_spans.add((row.cid,row.type,row.start,row.end))
        gold_spans_loose.add((row.cid,row.start,row.end))
        gold_types.add((row.cid,row.type))

    # precision = true_pos / true_pos + false_pos
    # recall = true_pos / true_pos + false_neg
    # f_1 = 2 * prec * rec / (prec + rec)

    results = {'TOTAL': {'STRICT': {},'SPANS': {},'TYPES': {}}}

    # Overall evaluation
    # strict: spans + type must match
    strict_p = float(len(pred_spans)) and float( len(gold_spans.intersection(pred_spans))) / len(pred_spans)
    strict_r = float(len(gold_spans)) and float( len(gold_spans.intersection(pred_spans))) / len(gold_spans)
    strict_f = (strict_p + strict_r) and 2 * strict_p * strict_r / (strict_p + strict_r)
    results['TOTAL']['STRICT']['prec'] = strict_p
    results['TOTAL']['STRICT']['rec'] = strict_r
    results['TOTAL']['STRICT']['f1'] = strict_f

    # spans: spans must match
    spans_p = float(len(pred_spans_loose)) and float( len(gold_spans_loose.intersection(pred_spans_loose))) / len(pred_spans_loose)
    spans_r = float(len(gold_spans_loose)) and float( len(gold_spans_loose.intersection(pred_spans_loose))) / len(gold_spans_loose)
    spans_f = (spans_p + spans_r) and 2 * spans_p * spans_r / (spans_p + spans_r)
    results['TOTAL']['SPANS']['prec'] = spans_p
    results['TOTAL']['SPANS']['rec'] = spans_r
    results['TOTAL']['SPANS']['f1'] = spans_f

    # detection mode: only types must match (per post)
    types_p = float(len(pred_types)) and float( len(gold_types.intersection(pred_types))) / len(pred_types)
    types_r = float(len(gold_types)) and float( len(gold_types.intersection(pred_types))) / len(gold_types)
    types_f = (types_p + types_r) and 2 * types_p * types_r / (types_p + types_r)
    results['TOTAL']['TYPES']['prec'] = types_p
    results['TOTAL']['TYPES']['rec'] = types_r
    results['TOTAL']['TYPES']['f1'] = types_f

    print("STRICT:\n ",strict_p,strict_r,strict_f)
    print("SPANS:\n ",spans_p,spans_r,spans_f)
    print("TYPES:\n ",types_p,types_r,types_f)
    return(results)

## Make submission file function

In [86]:
import csv
import zipfile
import os


def make_submission_task1(data, name):
    submission = data[["document","comment_id","flausch"]]
    for f in submission["flausch"]:
        if (f != "yes" and f != "no"):
            raise Exception("flausch prediction missing")
    csv_filename = submission_path + name + ".csv"
    zip_filename = submission_path + name + ".zip"
    submission.to_csv(csv_filename, index=False, quoting=csv.QUOTE_ALL)
    # make zip file
    with zipfile.ZipFile(zip_filename, 'w') as zipf:
      zipf.write(csv_filename, os.path.basename(csv_filename))

    print(f"Submission saved to {csv_filename} and zipped to {zip_filename}")

In [87]:
import zipfile
import os

def make_submission_task2(data, name):
    submission = data[["document","comment_id","type","start","end"]]
    for f in submission["start"]:
        if not type(f) is int:
            raise Exception("start prediction missing")
    for f in submission["end"]:
        if not type(f) is int:
            raise Exception("end prediction missing")
    csv_filename = submission_path + name + ".csv"
    zip_filename = submission_path + name + ".zip"
    submission.to_csv(csv_filename, index=False, quoting=csv.QUOTE_ALL)
    # make zip file
    with zipfile.ZipFile(zip_filename, 'w') as zipf:
      zipf.write(csv_filename, os.path.basename(csv_filename))

    print(f"Submission saved to {csv_filename} and zipped to {zip_filename}")

## Task 1

#### BERT model gBert-large: binary classifier: yes/no flausch

In [88]:
from datasets import Dataset

test_task1_dataset = Dataset.from_pandas(test_data_task1)
test_task1_dataset

Dataset({
    features: ['document', 'comment_id', 'comment', 'flausch', 'translated', 'spelling_corrected', 'sentiment_orig', 'sentiment_spelling_corrected', 'sentiment_translated', 'sentiment_anger', 'sentiment_disgust', 'sentiment_fear', 'sentiment_joy', 'sentiment_neutral', 'sentiment_sadness', 'sentiment_surprise', 'id'],
    num_rows: 3706
})

In [89]:
def apply_task1_pipeline(batch,pipeline,column,tokenizer_kwargs):
    texts = batch[column]
    results_for_batch = pipeline(texts, **tokenizer_kwargs)
    predictions = []
    top_scores = [] # List to store the scores of the top prediction

    for top_pred_item in results_for_batch:
        # top_pred_item ist ein Dictionary
        # Beispiel: {'label': 'POSITIVE', 'score': 0.99}
        predictions.append(top_pred_item['label'])
        top_scores.append(top_pred_item['score'])

    # Return a dictionary with the new columns, matching the batch size
    return {'prediction': predictions, 'score': top_scores}

In [90]:
from transformers import pipeline

def make_predictions_task1(model_name, column, access_token=access_token):
    if not access_token:
        raise ValueError("Access token is required to use the Hugging Face Hub.")
    print(f"Using model: {model_name}")
    print(f"Using access token: {access_token}")
    pipe = pipeline("text-classification", model=model_name, token=access_token)
    tokenizer_kwargs = {'padding':True,'truncation':True,'max_length':512}
        # for our test set 12 minutes on local machine on colab ~ 1 minute
    prediction_dataset = test_task1_dataset.map(
        apply_task1_pipeline,
        batched=True,
        batch_size=16,
        num_proc=1,
        fn_kwargs={"pipeline": pipe, "column": column, "tokenizer_kwargs": tokenizer_kwargs}
    )
    return prediction_dataset

In [91]:
file_gold = path + "gold_data_task1.csv"

In [92]:
# prediction with BERT model
# Careful: takes some time to predict with all models on all columns

checkpoint = "Wiebke/results_flausch_classification_"

# german models on spelling corrected comments and on original comments
for my_model in ["bert-base-german-cased", "gbert-large"]:
    for column in ["spelling_corrected", "comment"]:
        # German models gBERT-large and bert-base-german-cased and multilingual model roberta-large
        model_name = checkpoint + my_model + "_" + column
        prediction_dataset  = make_predictions_task1(model_name, column)
        submission = pd.DataFrame(prediction_dataset)
        submission["flausch"] = submission["prediction"]
        make_submission_task1(submission,"test_submission_task1_" + my_model + "_" + column)
        file_pred = submission_path + "test_submission_task1_"  + my_model  + "_" + column + ".csv"
        print("\nEvaluation for configuration", my_model, column)
        binary_eval(file_gold, file_pred)



# english model on translated comments
name =  "roberta-large"
column = "translated"
model_name = model= checkpoint + name + "_" + column
pipe = pipeline("text-classification", model=model_name, token=access_token)
tokenizer_kwargs = {'padding':True,'truncation':True,'max_length':512}
prediction_dataset  = make_predictions_task1(model_name, column)
submission = pd.DataFrame(prediction_dataset)
submission["flausch"] = submission["prediction"]
make_submission_task1(submission,"test_submission_task1_" + name + "_" + column)
file_pred = submission_path + "test_submission_task1_"  + name  + "_" + column + ".csv"
print("\nEvaluation for configuration", name, column)
binary_eval(file_gold, file_pred)

Using model: Wiebke/results_flausch_classification_bert-base-german-cased_spelling_corrected
Using access token: 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

config.json:   0%|          | 0.00/773 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

Device set to use cuda:0

Map:   0%|          | 0/3706 [00:00<?, ? examples/s]

Submission saved to /content/drive/MyDrive/FlauschData/submission/test_submission_task1_bert-base-german-cased_spelling_corrected.csv and zipped to /content/drive/MyDrive/FlauschData/submission/test_submission_task1_bert-base-german-cased_spelling_corrected.zip

Evaluation for configuration bert-base-german-cased spelling_corrected
TASK 1: BINARY CLASSIFICATION
=============================
Precision:	 0.8810
Recall:		 0.8793
F-score:	 0.8802
Using model: Wiebke/results_flausch_classification_bert-base-german-cased_comment
Using access token: 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

config.json:   0%|          | 0.00/773 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.29k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/240k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/729k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

Device set to use cuda:0

Map:   0%|          | 0/3706 [00:00<?, ? examples/s]

Submission saved to /content/drive/MyDrive/FlauschData/submission/test_submission_task1_bert-base-german-cased_comment.csv and zipped to /content/drive/MyDrive/FlauschData/submission/test_submission_task1_bert-base-german-cased_comment.zip

Evaluation for configuration bert-base-german-cased comment
TASK 1: BINARY CLASSIFICATION
=============================
Precision:	 0.8849
Recall:		 0.8841
F-score:	 0.8845
Using model: Wiebke/results_flausch_classification_gbert-large_spelling_corrected
Using access token: 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

config.json:   0%|          | 0.00/751 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.29k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/240k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/729k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

Device set to use cuda:0

Map:   0%|          | 0/3706 [00:00<?, ? examples/s]

Submission saved to /content/drive/MyDrive/FlauschData/submission/test_submission_task1_gbert-large_spelling_corrected.csv and zipped to /content/drive/MyDrive/FlauschData/submission/test_submission_task1_gbert-large_spelling_corrected.zip

Evaluation for configuration gbert-large spelling_corrected
TASK 1: BINARY CLASSIFICATION
=============================
Precision:	 0.8866
Recall:		 0.9061
F-score:	 0.8963
Using model: Wiebke/results_flausch_classification_gbert-large_comment
Using access token: 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

config.json:   0%|          | 0.00/751 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.29k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/240k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/729k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

Device set to use cuda:0

Map:   0%|          | 0/3706 [00:00<?, ? examples/s]

Submission saved to /content/drive/MyDrive/FlauschData/submission/test_submission_task1_gbert-large_comment.csv and zipped to /content/drive/MyDrive/FlauschData/submission/test_submission_task1_gbert-large_comment.zip

Evaluation for configuration gbert-large comment
TASK 1: BINARY CLASSIFICATION
=============================
Precision:	 0.8805
Recall:		 0.9320
F-score:	 0.9055

config.json:   0%|          | 0.00/799 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.25k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.56M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

Device set to use cuda:0

Using model: Wiebke/results_flausch_classification_roberta-large_translated
Using access token: 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

Device set to use cuda:0

Map:   0%|          | 0/3706 [00:00<?, ? examples/s]

Submission saved to /content/drive/MyDrive/FlauschData/submission/test_submission_task1_roberta-large_translated.csv and zipped to /content/drive/MyDrive/FlauschData/submission/test_submission_task1_roberta-large_translated.zip

Evaluation for configuration roberta-large translated
TASK 1: BINARY CLASSIFICATION
=============================
Precision:	 0.8853
Recall:		 0.8649
F-score:	 0.8750

(0.8852941176470588, 0.8649425287356322, 0.875)

In [93]:
# features.csv file is updated with name + "_yes_" + column column for scores for "yes"
df = pd.DataFrame(prediction_dataset).reset_index(drop=True)
df.loc[df["prediction"] == "no", "score"] = 1-df["score"]
# if path + features.csv does not exist, it will be created
if not os.path.exists(path + "features.csv"):
    features = test_data_task1[["id","document","comment_id"]].copy().reset_index(drop=True)
else:
    features = pd.read_csv(path + "features.csv").reset_index(drop=True)
features[name + "_yes_" + column] =  float('nan')
df["score"] = df["score"].astype(float)

score_dict = dict(zip(df["id"], df["score"]))

features[name + "_yes_" + column] = features["id"].map(score_dict)

features = features.drop(columns=[x for x in features.columns if x.startswith("Unnamed")])

features.to_csv(path + "features.csv")

In [94]:
features.head(3)

,id,set,gbert-large_yes_comment,bert-base-german-cased_yes_comment,bert-base-german-cased_yes_spelling_corrected,gbert-large_yes_spelling_corrected,roberta-large_yes_translated
0,NDY-003_1,train,NaN,NaN,NaN,NaN,NaN
1,NDY-003_2,train,NaN,NaN,NaN,NaN,NaN
2,NDY-003_3,train,NaN,NaN,NaN,NaN,NaN

### Compare BERT classification models

In [95]:
features = pd.read_csv(path + "features.csv")

german_models = ["gbert-large", "bert-base-german-cased"]
english_models = ["roberta-large"]
german_columns = ["comment", "spelling_corrected"]
english_columns = ["translated"]
testdata = features[features["set"]=="test"].reset_index(drop=True)

gold = pd.read_csv(path + "gold_data_task1.csv")
gold = make_id_column(gold)
gold = gold[["id", "flausch"]]
testdata = testdata.merge(gold, on="id")

test = testdata.copy()

cnames = []
for m in german_models:
    for c in german_columns:
        cname = m + "_yes_" + c
        cnames.append(cname)

for m in english_models:
    for c in english_columns:
        cname = m + "_yes_" + c
        cnames.append(cname)

for c in cnames:
    test[c] = test[c].apply(lambda x: "yes" if x > 0.5 else "no")

test.head(3)

,Unnamed: 0,id,set,gbert-large_yes_comment,bert-base-german-cased_yes_comment,bert-base-german-cased_yes_spelling_corrected,gbert-large_yes_spelling_corrected,roberta-large_yes_translated,flausch
0,4,NDY-003_5,test,yes,yes,yes,yes,yes,yes
1,13,NDY-003_14,test,no,no,no,no,no,no
2,40,NDY-003_41,test,yes,yes,yes,yes,no,yes

In [96]:
import numpy as np
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score, accuracy_score
for c in cnames:
    gold = test["flausch"]
    pred = test[c]
    print()
    print(c)
    print("weighted F1 score:", f1_score(gold,pred,average="weighted"))
    print("accuracy:", accuracy_score(gold,pred))
    print(classification_report(gold,pred))

gbert-large_yes_comment
weighted F1 score: 0.9456839415000668
accuracy: 0.9452239611440907
              precision    recall  f1-score   support

          no       0.97      0.95      0.96      2662
         yes       0.88      0.93      0.91      1044

    accuracy                           0.95      3706
   macro avg       0.93      0.94      0.93      3706
weighted avg       0.95      0.95      0.95      3706


gbert-large_yes_spelling_corrected
weighted F1 score: 0.9411003608844272
accuracy: 0.9409066378845116
              precision    recall  f1-score   support

          no       0.96      0.95      0.96      2662
         yes       0.89      0.91      0.90      1044

    accuracy                           0.94      3706
   macro avg       0.92      0.93      0.93      3706
weighted avg       0.94      0.94      0.94      3706


bert-base-german-cased_yes_comment
weighted F1 score: 0.9349608447726742
accuracy: 0.9349703184025904
              precision    recall  f1-score   support

          no       0.95      0.95      0.95      2662
         yes       0.88      0.88      0.88      1044

    accuracy                           0.93      3706
   macro avg       0.92      0.92      0.92      3706
weighted avg       0.93      0.93      0.93      3706


bert-base-german-cased_yes_spelling_corrected
weighted F1 score: 0.9325221513614445
accuracy: 0.9325418240690772
              precision    recall  f1-score   support

          no       0.95      0.95      0.95      2662
         yes       0.88      0.88      0.88      1044

    accuracy                           0.93      3706
   macro avg       0.92      0.92      0.92      3706
weighted avg       0.93      0.93      0.93      3706


roberta-large_yes_translated
weighted F1 score: 0.9301346216953567
accuracy: 0.9303831624392876
              precision    recall  f1-score   support

          no       0.95      0.96      0.95      2662
         yes       0.89      0.86      0.88      1044

    accuracy                           0.93      3706
   macro avg       0.92      0.91      0.91      3706
weighted avg       0.93      0.93      0.93      3706

In [97]:
id_false = test[test["gbert-large_yes_comment"] != test["flausch"]]["id"]
false = testdata[testdata["id"].isin(id_false)]
false

,Unnamed: 0,id,set,gbert-large_yes_comment,bert-base-german-cased_yes_comment,bert-base-german-cased_yes_spelling_corrected,gbert-large_yes_spelling_corrected,roberta-large_yes_translated,flausch
21,261,NDY-003_262,test,0.991680,0.989212,0.993828,0.991255,0.995281,no
22,263,NDY-003_264,test,0.990066,0.158031,0.317640,0.972652,0.994509,no
30,314,NDY-003_315,test,0.940336,0.487242,0.991803,0.989425,0.993041,no
87,943,NDY-003_944,test,0.970248,0.003784,0.004983,0.991856,0.992910,no
92,977,NDY-003_978,test,0.968321,0.001037,0.008553,0.532543,0.954395,no
...,...,...,...,...,...,...,...,...,...
3567,35681,NDY-252_132,test,0.716943,0.005428,0.113768,0.922664,0.022369,no
3615,36236,NDY-252_687,test,0.685843,0.932554,0.377381,0.032994,0.989608,no
3659,36639,NDY-274_91,test,0.943479,0.079387,0.151630,0.020367,0.990125,no
3679,36811,NDY-274_263,test,0.042193,0.000325,0.001814,0.013124,0.003413,yes
3691,36887,NDY-285_34,test,0.964197,0.006723,0.007373,0.816801,0.012434,no

In [98]:
### train a metaclassifier

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X = testdata[cnames]
y = testdata["flausch"]

X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2, random_state=42)



model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nRandom Forest")
print("F1 score weighted:",f1_score(y_test, y_pred,average="weighted"))
print("accuracy:",accuracy_score(y_test, y_pred))

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nDecision Tree")
print("F1 score weighted:",f1_score(y_test, y_pred,average="weighted"))
print("accuracy:",accuracy_score(y_test, y_pred))



model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nLogistic Regression")
print("F1 score weighted:",f1_score(y_test, y_pred,average="weighted"))
print("accuracy:",accuracy_score(y_test, y_pred))
print("coefficient    ", "configuration")
for i in range(len(X_test.columns)):
    print(model.coef_[0][i], " ", X_test.columns[i])


print(classification_report(y_test, y_pred))

Random Forest
F1 score weighted: 0.9538939248821557
accuracy: 0.954177897574124

Decision Tree
F1 score weighted: 0.9205443183562734
accuracy: 0.9204851752021563

Logistic Regression
F1 score weighted: 0.9593181690136667
accuracy: 0.9595687331536388
coefficient     configuration
2.650286530679682   gbert-large_yes_comment
1.3588981616268987   gbert-large_yes_spelling_corrected
0.8798059135290492   bert-base-german-cased_yes_comment
1.003752282660399   bert-base-german-cased_yes_spelling_corrected
0.8682001600338847   roberta-large_yes_translated
              precision    recall  f1-score   support

          no       0.97      0.98      0.97       536
         yes       0.94      0.91      0.93       206

    accuracy                           0.96       742
   macro avg       0.95      0.94      0.95       742
weighted avg       0.96      0.96      0.96       742

## Task 2

### Task2: Token classifier that uses BIO-scheme

BERT model gBERT-large: Token classification BIO scheme

In [99]:
from transformers import pipeline
if flausch_mode == "all":
  checkpoint = "Wiebke/flausch_span_gbert-large_all"
else:
  checkpoint = "Wiebke/flausch_span_gbert-large"

pipe = pipeline("token-classification", model=checkpoint)
pipe("das habt ihr großartig gmacht. Macht weiter so. Nächsten Monat wird es warm. Team Sommer!!!!")

Device set to use cuda:0

[{'entity': 'B-compliment',
  'score': np.float32(0.9659506),
  'index': 1,
  'word': 'das',
  'start': 0,
  'end': 3},
 {'entity': 'I-compliment',
  'score': np.float32(0.98921645),
  'index': 2,
  'word': 'habt',
  'start': 4,
  'end': 8},
 {'entity': 'I-compliment',
  'score': np.float32(0.98224235),
  'index': 3,
  'word': 'ihr',
  'start': 9,
  'end': 12},
 {'entity': 'I-compliment',
  'score': np.float32(0.9807341),
  'index': 4,
  'word': 'großartig',
  'start': 13,
  'end': 22},
 {'entity': 'I-compliment',
  'score': np.float32(0.98180145),
  'index': 5,
  'word': 'g',
  'start': 23,
  'end': 24},
 {'entity': 'I-compliment',
  'score': np.float32(0.9873431),
  'index': 6,
  'word': '##macht',
  'start': 24,
  'end': 29},
 {'entity': 'B-encouragement',
  'score': np.float32(0.938666),
  'index': 8,
  'word': 'Macht',
  'start': 31,
  'end': 36},
 {'entity': 'I-encouragement',
  'score': np.float32(0.92488337),
  'index': 9,
  'word': 'weiter',
  'start': 37,
  'end': 43},
 {'entity': 'I-encouragement',
  'score': np.float32(0.9418827),
  'index': 10,
  'word': 'so',
  'start': 44,
  'end': 46}]

In [100]:
texts = ["Hunde sind Säugetiere", "großen Dank", "das habt ihr großartig gmacht. Macht weiter so. Nächsten Monat wird es warm. Team Sommer!!!!"]
pipe(texts)

[[],
 [],
 [{'entity': 'B-compliment',
   'score': np.float32(0.9659506),
   'index': 1,
   'word': 'das',
   'start': 0,
   'end': 3},
  {'entity': 'I-compliment',
   'score': np.float32(0.98921645),
   'index': 2,
   'word': 'habt',
   'start': 4,
   'end': 8},
  {'entity': 'I-compliment',
   'score': np.float32(0.98224235),
   'index': 3,
   'word': 'ihr',
   'start': 9,
   'end': 12},
  {'entity': 'I-compliment',
   'score': np.float32(0.9807341),
   'index': 4,
   'word': 'großartig',
   'start': 13,
   'end': 22},
  {'entity': 'I-compliment',
   'score': np.float32(0.98180145),
   'index': 5,
   'word': 'g',
   'start': 23,
   'end': 24},
  {'entity': 'I-compliment',
   'score': np.float32(0.9873431),
   'index': 6,
   'word': '##macht',
   'start': 24,
   'end': 29},
  {'entity': 'B-encouragement',
   'score': np.float32(0.938666),
   'index': 8,
   'word': 'Macht',
   'start': 31,
   'end': 36},
  {'entity': 'I-encouragement',
   'score': np.float32(0.92488337),
   'index': 9,
   'word': 'weiter',
   'start': 37,
   'end': 43},
  {'entity': 'I-encouragement',
   'score': np.float32(0.9418827),
   'index': 10,
   'word': 'so',
   'start': 44,
   'end': 46}]]

In [101]:
def apply_task2_pipeline(batch,pipeline,column):
    texts = batch[column]
    results_for_batch = pipeline(texts)

    types = []
    starts = []
    ends = []
    scores = []

    for single_text_result in results_for_batch:
        # single_text_result ist eine Liste von Dictionaries
        # Beispiel: [{'entity': 'B-gratitude', 'score': 0.87086165, 'index': 1,  'word': 'großen', 'start': 0,  'end': 6},
        #{'entity': 'I-gratitude','score': 0.78514546, 'index': 2,'word': 'Dank','start': 7,'end': 11}],
        type = []
        start = []
        end = []
        score = []
        for dic in single_text_result:
            type.append(dic['entity'])
            start.append(dic['start'])
            end.append(dic['end'])
            score.append(dic['score'])

        types.append(type)
        starts.append(start)
        ends.append(end)
        scores.append(score)

    # Return a dictionary with the new columns, matching the batch size
    return {'types': types, 'starts': starts, 'ends': ends, 'scores': scores}

In [102]:
from datasets import Dataset

test_task2_dataset = Dataset.from_pandas(test_data_task2)

In [103]:
test_task2_dataset

Dataset({
    features: ['document', 'comment_id', 'comment', 'flausch', 'translated', 'spelling_corrected', 'sentiment_orig', 'sentiment_spelling_corrected', 'sentiment_translated', 'sentiment_anger', 'sentiment_disgust', 'sentiment_fear', 'sentiment_joy', 'sentiment_neutral', 'sentiment_sadness', 'sentiment_surprise', 'id'],
    num_rows: 3706
})

In [104]:
prediction_dataset = test_task2_dataset.map(
    apply_task2_pipeline,
    batched=True,
    batch_size=16,
    num_proc=1,
    fn_kwargs={"pipeline": pipe, "column": "comment"}
)

Map:   0%|          | 0/3706 [00:00<?, ? examples/s]

In [105]:
def map_to_type(string):
    return string.split("-")[1]



def merge_types(row):
    if len(row["types"]) == 0:
        return row
    current_t = map_to_type(row["types"][0])
    filter = [1]
    filter_end = [0]
    if len(row["types"]) > 1:
        for t in row["types"][1:]:
            if t == "I-" + current_t:
                filter.append(0)
                filter_end.append(0)
            else:
                filter_end[-1] = 2
                current_t = map_to_type(t)
                filter.append(1)
                filter_end.append(0)
        filter_end[-1] = 2
    filter_end[-1] = 2
    row["types"] = [row["types"][i] for i in range(len(filter)) if filter[i] == 1]
    row["starts"] = [row["starts"][i] for i in range(len(filter)) if filter[i] == 1]
    row["ends"] = [row["ends"][i] for i in range(len(filter_end)) if filter_end[i] == 2]
    if len(row["types"]) != len(row["starts"]):
        print("problem types-Länge ungleich starts-Länge")
    if len(row["types"]) != len(row["ends"]):
        print("problem types-Länge ungleich ends-Länge")
        print(filter)
        print(filter_end)
        print()
    return row

In [106]:

def output_task2(df):
#    df["types"] = df["types"].apply(lambda x: list(map(map_to_type, x)))
    df = df.apply(merge_types, axis=1)
    output = []
    for i in range(df.shape[0]):
        types, starts, ends = df.loc[i][["types","starts","ends"]]
        if len(types) > 0:
            document, comment_id = df.loc[i][["document", "comment_id"]]
            for j in range(len(types)):
                output.append({"document": document,"comment_id": comment_id,
                               "type": map_to_type(types[j]), "start": starts[j],"end":ends[j]})
    return pd.DataFrame(output)

In [107]:
import os

df = pd.DataFrame(prediction_dataset)
out_task2 = output_task2(df)
make_submission_task2(out_task2, "test_submission_task2_gbert")

Submission saved to /content/drive/MyDrive/FlauschData/submission/test_submission_task2_gbert.csv and zipped to /content/drive/MyDrive/FlauschData/submission/test_submission_task2_gbert.zip

In [108]:
df.head(3)

,document,comment_id,comment,flausch,translated,spelling_corrected,sentiment_orig,sentiment_spelling_corrected,sentiment_translated,sentiment_anger,...,sentiment_fear,sentiment_joy,sentiment_neutral,sentiment_sadness,sentiment_surprise,id,types,starts,ends,scores
0,NDY-003,5,das ist so geil :),yes,that's so awesome :),Das ist so geil -).,0.7,0.7,0.750000,0.001721,...,0.000910,0.938277,0.021804,0.003207,0.032559,NDY-003_5,"[B-positive feedback, I-positive feedback, I-p...","[0, 4, 8, 11, 13, 16, 17]","[3, 7, 10, 13, 15, 17, 18]","[0.9783414602279663, 0.9878492951393127, 0.988..."
1,NDY-003,14,Wäre auch lieb wenn ihr ihr auf meinen Post an...,no,Would also be nice if you could answer my post...,Wäre auch lieb wenn ihr ihr auf meinen Post an...,1.0,1.0,0.300000,0.004424,...,0.001319,0.055112,0.849691,0.013397,0.073176,NDY-003_14,[],[],[],[]
2,NDY-003,41,@Der1999Ottifant SOOOOOOOOOOOOOOOOO Viele Schö...,yes,@The 1999Ottifant SOOOOOOOOOOOOOOOOO Many beau...,') Der 1999Ottifant SOOOOOOOOOOOOOOOOOOOOO Vie...,1.0,1.0,0.616667,0.005008,...,0.001449,0.374928,0.045861,0.067824,0.504184,NDY-003_41,[],[],[],[]

In [109]:
file_gold = path + "gold_data_task2.csv"
file_pred = submission_path + "test_submission_task2_gbert" + ".csv"
results = fine_grained_flausch_by_label(file_gold, file_pred)

typeList = gold_data_task2["type"].unique()
all = []
for t in typeList:
    print(t)
    print(pd.DataFrame(results[t]))
    print()

STRICT:
  0.6072874493927125 0.6921555702043507 0.6469500924214417
SPANS:
  0.6402544823597455 0.7297297297297297 0.6820702402957486
TYPES:
  0.7437825332562175 0.8477257745550428 0.7923598274799754
positive feedback
        STRICT     TYPES
prec  0.668156  0.854077
rec   0.735547  0.900452
f1    0.700234  0.876652

affection declaration
        STRICT     TYPES
prec  0.572816  0.818182
rec   0.702381  0.868421
f1    0.631016  0.842553

group membership
        STRICT     TYPES
prec  0.470588  0.866667
rec   0.380952  0.722222
f1    0.421053  0.787879

encouragement
        STRICT     TYPES
prec  0.571429  0.909091
rec   0.643678  0.843373
f1    0.605405  0.875000

compliment
        STRICT     TYPES
prec  0.527221  0.824219
rec   0.689139  0.890295
f1    0.597403  0.855984

ambiguous
        STRICT     TYPES
prec  0.360000  0.611111
rec   0.409091  0.500000
f1    0.382979  0.550000

implicit
        STRICT     TYPES
prec  0.200000  0.400000
rec   0.090909  0.181818
f1    0.125000  0.250000

sympathy
      STRICT     TYPES
prec     0.0  0.250000
rec      0.0  0.200000
f1       0.0  0.222222

agreement
        STRICT     TYPES
prec  0.166667  0.333333
rec   0.062500  0.125000
f1    0.090909  0.181818

gratitude
        STRICT     TYPES
prec  0.800000  1.000000
rec   0.695652  0.818182
f1    0.744186  0.900000

#### Fehleranalyse (not ready)

In [110]:
dfa= out_task2
dfb =  gold_data_task2

# Finde die Zeilen in df2, die auch in df1 sind
# Ein 'merge' mit 'indicator=True' zeigt an, woher die Zeilen kommen
merged_dfb = dfb.merge(dfa, how='left', indicator=True)
merged_dfa = dfa.merge(dfb, how='left', indicator=True)


# Filtere nur die Zeilen, die NICHT in df1 vorkommen
# '_merge' == 'left_only' bedeutet, die Zeile war nur in df2
dfb_cleaned_all_cols = merged_dfb[merged_dfb['_merge'] == 'left_only'].drop(columns=['_merge'])
dfa_cleaned_all_cols = merged_dfa[merged_dfa['_merge'] == 'left_only'].drop(columns=['_merge'])

In [111]:
dfa.shape, dfa_cleaned_all_cols.shape, dfb.shape, dfb_cleaned_all_cols.shape

((1729, 5), (679, 5), (1517, 5), (467, 5))

In [112]:
dfa_cleaned_all_cols.loc[10:25]

   document  comment_id               type  start  end
12  NDY-003         166  positive feedback      0   15
13  NDY-003         218  positive feedback      3    9
16  NDY-003         262  positive feedback      0    4
17  NDY-003         264  positive feedback      0   27
18  NDY-003         264  positive feedback     28   90
19  NDY-003         267         compliment     34   39
20  NDY-003         267         compliment     43   63
25  NDY-003         345      encouragement     92  132

In [113]:
dfb_cleaned_all_cols.loc[10:25]

   document  comment_id                   type  start  end
12  NDY-003          97          encouragement      0   67
15  NDY-003         145      positive feedback    194  267
16  NDY-003         166  affection declaration      0   15
19  NDY-003         252  affection declaration      0   37
20  NDY-003         267             compliment      0   40
21  NDY-003         267      positive feedback     43   63

In [114]:
document = "NDY-003"
comment_id = 76

# get prediction_dataset and gold_data_task2 mit document and comment_id

filtered_rows_gold = gold_data_task2[(gold_data_task2['document'] == document) & (gold_data_task2['comment_id'] == comment_id)]
print(filtered_rows_gold)

filtered_rows_out = out_task2[(out_task2['document'] == document) & (out_task2['comment_id'] == comment_id)]

print()
print(filtered_rows_out)

  document  comment_id                   type  start  end
3  NDY-003          76  affection declaration     24   59
4  NDY-003          76       group membership     60   86
5  NDY-003          76      positive feedback    135  173
6  NDY-003          76  affection declaration    176  204
7  NDY-003          76      positive feedback    209  248
8  NDY-003          76      positive feedback    251  286
9  NDY-003          76  affection declaration    342  353

  document  comment_id                   type  start  end
2  NDY-003          76  affection declaration     24   59
3  NDY-003          76       group membership     60  134
4  NDY-003          76      positive feedback    135  175
5  NDY-003          76  affection declaration    176  204
6  NDY-003          76      positive feedback    209  286
7  NDY-003          76  affection declaration    342  353

Beobachtung: eigene sind häufiger etwas zu lang.

### Task2: Alternative approach -- first flausch span detection then flausch span classification

In [115]:
detector = "Wiebke/flausch_span_gbert-large_non_labeled_spans"
classifier = "Wiebke/results_flausch_classification_gbert-large_span_classifier"

# test whether a classifier that was trained on all spans (including not flausch spans performs better)
# result: no
#classifier = "Wiebke/task2_flausch_classification_gbert-large_span_classifier_with_nonspan"

In [116]:
from transformers import pipeline

pipe = pipeline("token-classification", model=detector)

config.json:   0%|          | 0.00/739 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

Device set to use cuda:0

In [117]:
pipe("das habt ihr großartig gmacht. Macht weiter so. Nächsten Monat wird es warm. Team Sommer!!!!")

[{'entity': 'B-span',
  'score': np.float32(0.99427795),
  'index': 1,
  'word': 'das',
  'start': 0,
  'end': 3},
 {'entity': 'I-span',
  'score': np.float32(0.9980672),
  'index': 2,
  'word': 'habt',
  'start': 4,
  'end': 8},
 {'entity': 'I-span',
  'score': np.float32(0.9978638),
  'index': 3,
  'word': 'ihr',
  'start': 9,
  'end': 12},
 {'entity': 'I-span',
  'score': np.float32(0.9969014),
  'index': 4,
  'word': 'großartig',
  'start': 13,
  'end': 22},
 {'entity': 'I-span',
  'score': np.float32(0.99586594),
  'index': 5,
  'word': 'g',
  'start': 23,
  'end': 24},
 {'entity': 'I-span',
  'score': np.float32(0.998458),
  'index': 6,
  'word': '##macht',
  'start': 24,
  'end': 29},
 {'entity': 'B-span',
  'score': np.float32(0.9943455),
  'index': 8,
  'word': 'Macht',
  'start': 31,
  'end': 36},
 {'entity': 'I-span',
  'score': np.float32(0.99189645),
  'index': 9,
  'word': 'weiter',
  'start': 37,
  'end': 43},
 {'entity': 'I-span',
  'score': np.float32(0.99535733),
  'index': 10,
  'word': 'so',
  'start': 44,
  'end': 46}]

In [118]:
test_task2_dataset = Dataset.from_pandas(test_data_task2)

In [119]:
prediction_dataset = test_task2_dataset.map(
    apply_task2_pipeline,
    batched=True,
    batch_size=16,
    num_proc=1,
    fn_kwargs={"pipeline": pipe, "column": "comment"}
)

Map:   0%|          | 0/3706 [00:00<?, ? examples/s]

In [120]:
df = pd.DataFrame(prediction_dataset)
out_task2 = output_task2(df)

In [121]:
out_task2 = out_task2.rename(columns={"type": "temp_type"})

In [122]:
test_data_task1.columns

Index(['document', 'comment_id', 'comment', 'flausch', 'translated',
       'spelling_corrected', 'sentiment_orig', 'sentiment_spelling_corrected',
       'sentiment_translated', 'sentiment_anger', 'sentiment_disgust',
       'sentiment_fear', 'sentiment_joy', 'sentiment_neutral',
       'sentiment_sadness', 'sentiment_surprise', 'id'],
      dtype='object')

In [123]:
my_columns = ['document', 'comment_id', 'comment',  'id']
out_task2 = pd.merge(out_task2, test_data_task1[my_columns], on=["comment_id","document"], how = "left")

In [124]:
out_task2["span"] = out_task2.apply(lambda row: row["comment"][row["start"]:(row["end"]+1)], axis=1)

In [125]:
out_task2.head(3)

,document,comment_id,temp_type,start,end,comment,id,span
0,NDY-003,5,span,0,18,das ist so geil :),NDY-003_5,das ist so geil :)
1,NDY-003,41,span,17,58,@Der1999Ottifant SOOOOOOOOOOOOOOOOO Viele Schö...,NDY-003_41,SOOOOOOOOOOOOOOOOO Viele Schöne Daumen :)
2,NDY-003,71,span,0,17,Ihr süßeen ♥ ' :D,NDY-003_71,Ihr süßeen ♥ ' :D

In [126]:
pipe = pipeline("text-classification", model=classifier)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

Device set to use cuda:0

In [127]:
# apply pipe to column "span" and write prediction into column "type"

def apply_span_classification_pipeline(row, pipeline):
    text = row['span']
    result = pipeline(text)
    # Assuming the pipeline returns a list of dictionaries and we need the label of the first one
    if result:
        return result[0]['label']
    return None

out_task2['type'] = out_task2.apply(lambda row: apply_span_classification_pipeline(row, pipe), axis=1)

In [128]:
out_task2.head(3)

,document,comment_id,temp_type,start,end,comment,id,span,type
0,NDY-003,5,span,0,18,das ist so geil :),NDY-003_5,das ist so geil :),positive feedback
1,NDY-003,41,span,17,58,@Der1999Ottifant SOOOOOOOOOOOOOOOOO Viele Schö...,NDY-003_41,SOOOOOOOOOOOOOOOOO Viele Schöne Daumen :),positive feedback
2,NDY-003,71,span,0,17,Ihr süßeen ♥ ' :D,NDY-003_71,Ihr süßeen ♥ ' :D,affection declaration

In [129]:
make_submission_task2(out_task2, mode + "_test_submission_task2_gbert_2steps")

Submission saved to /content/drive/MyDrive/FlauschData/submission/train_test_submission_task2_gbert_2steps.csv and zipped to /content/drive/MyDrive/FlauschData/submission/train_test_submission_task2_gbert_2steps.zip

In [130]:
# final submission for task 2
if mode == "test":
  make_submission_task2(out_task2, "task2-predicted")

In [131]:
gold_data_task2 = pd.read_csv(path + "gold_data_task2.csv")
file_gold = path + "gold_data_task2.csv"
file_pred = submission_path + mode + "_test_submission_task2_gbert_2steps" + ".csv"
results = fine_grained_flausch_by_label(file_gold, file_pred)

typeList = gold_data_task2["type"].unique()
all = []
for t in typeList:
    print(t)
    print(pd.DataFrame(results[t]))
    print()

STRICT:
  0.7192530585962653 0.7363216875411998 0.7276872964169382
SPANS:
  0.7598197037990985 0.7778510217534608 0.7687296416938111
TYPES:
  0.8235672891178365 0.8431114040870138 0.8332247557003257
positive feedback
        STRICT     TYPES
prec  0.755772  0.873547
rec   0.765068  0.906486
f1    0.760391  0.889711

affection declaration
        STRICT     TYPES
prec  0.718631  0.862069
rec   0.750000  0.877193
f1    0.733981  0.869565

group membership
        STRICT     TYPES
prec  0.666667  0.823529
rec   0.571429  0.777778
f1    0.615385  0.800000

encouragement
        STRICT     TYPES
prec  0.732558  0.875000
rec   0.724138  0.843373
f1    0.728324  0.858896

compliment
        STRICT     TYPES
prec  0.693380  0.855422
rec   0.745318  0.898734
f1    0.718412  0.876543

ambiguous
        STRICT     TYPES
prec  0.428571  0.476190
rec   0.409091  0.454545
f1    0.418605  0.465116

implicit
        STRICT     TYPES
prec  0.181818  0.363636
rec   0.181818  0.363636
f1    0.181818  0.363636

sympathy
        STRICT     TYPES
prec  0.111111  0.125000
rec   0.200000  0.200000
f1    0.142857  0.153846

agreement
        STRICT     TYPES
prec  0.153846  0.153846
rec   0.125000  0.125000
f1    0.137931  0.137931

gratitude
        STRICT     TYPES
prec  0.818182  0.904762
rec   0.782609  0.863636
f1    0.800000  0.883721

In [132]:
out_task2["type"].value_counts()

type
positive feedback        823
compliment               287
affection declaration    263
encouragement             86
gratitude                 22
ambiguous                 21
group membership          18
agreement                 13
implicit                  11
sympathy                   9
Name: count, dtype: int64

# Data statistics

In [162]:
our_path  = google_path + "train" +"/"
own_train_data_task1 = pd.read_json(our_path + "train_task1.json")
own_train_data_task2 = pd.read_json(our_path + "train_task2.json")
own_test_data_task1 = pd.read_json(our_path + "test_task1.json")
own_test_data_task2 = pd.read_json(our_path + "test_task2.json")

In [233]:
test_path = google_path + "test_gold" +"/"
comp_test_data_task1 = pd.read_csv(test_path + "task1.csv")
comp_test_data_task2 = pd.read_csv(test_path + "task2.csv")
comp_test_comment = pd.read_csv(test_path + "comments.csv")

In [135]:
print("own_train_data_task1",own_train_data_task1.shape)
print("own_test_data_task1",own_test_data_task1.shape)
print("own_train_data_task2",own_train_data_task2.shape)
print("own_test_data_task2",own_test_data_task2.shape)
print("comp_test_data_task1", comp_test_data_task1.shape)
print("comp_test_data_task2", comp_test_data_task2.shape)

own_train_data_task1 (33351, 20)
own_test_data_task1 (3706, 20)
own_train_data_task2 (14282, 21)
own_test_data_task2 (1517, 21)
comp_test_data_task1 (9229, 3)
comp_test_data_task2 (5986, 5)

In [136]:
own_train_data_task2.head(3)

,document,comment_id,type,start,end,comment,flausch,translated,spelling_corrected,sentiment_orig,...,sentiment_translated,sentiment_anger,sentiment_disgust,sentiment_fear,sentiment_joy,sentiment_neutral,sentiment_sadness,sentiment_surprise,span,id
0,NDY-003,1,compliment,0,11,Respekt : o zu mir passt das heut vollkommen :...,yes,Respect : o to me this fits perfectly today :(...,Respekt - ob zu mir passt das heute vollkommen...,0.0,...,0.137500,0.317590,0.117705,0.004799,0.272843,0.234663,0.040224,0.012175,Respekt : o,NDY-003_1
1,NDY-003,1,compliment,48,71,Respekt : o zu mir passt das heut vollkommen :...,yes,Respect : o to me this fits perfectly today :(...,Respekt - ob zu mir passt das heute vollkommen...,0.0,...,0.137500,0.317590,0.117705,0.004799,0.272843,0.234663,0.040224,0.012175,Aber Respekt an euch ;),NDY-003_1
2,NDY-003,2,positive feedback,0,12,haha geil :D aber ich hab mich am anfang etwas...,yes,haha horny :D but I got a little scared at the...,Haha geil -Da aber ich hab mich am Anfang etwa...,0.7,...,0.503125,0.002527,0.001026,0.978153,0.002605,0.004189,0.009158,0.002342,haha geil :D,NDY-003_2

In [137]:
print("task1")
print("ratio flausch in own train data", own_train_data_task1[own_train_data_task1["flausch"]=="yes"].shape[0]/own_train_data_task1.shape[0])
print("ratio flausch in own test data", own_test_data_task1[own_test_data_task1["flausch"]=="yes"].shape[0]/own_test_data_task1.shape[0])
print("ratio flausch in gold competition test data", comp_test_data_task1[comp_test_data_task1["flausch"]=="yes"].shape[0]/comp_test_data_task1.shape[0])

print("")
print("average length of comments in own train data", own_train_data_task1["comment"].apply(lambda x: len(x)).mean())
print("average length of comments in own test data", own_test_data_task1["comment"].apply(lambda x: len(x)).mean())
print("average length of comments in gold competition test data", comp_test_comment["comment"].apply(lambda x: len(x)).mean())

task1
ratio flausch in own train data 0.2917153908428533
ratio flausch in own test data 0.2817053426875337
ratio flausch in gold competition test data 0.41250406327879513

average length of comments in own train data 58.270696530838656
average length of comments in own test data 59.01457096600108
average length of comments in gold competition test data 68.63452161664318

In [138]:
type_list = own_train_data_task2["type"].unique()

In [139]:
print("task2")
type_distribution = own_train_data_task2["type"].value_counts()/own_train_data_task2.shape[0]
print("distribution in own train data")
print(type_distribution.reindex(type_list))
type_distribution = own_test_data_task2["type"].value_counts()/own_test_data_task2.shape[0]
print("distribution in own test data")
print(type_distribution.reindex(type_list))
type_distribution = comp_test_data_task2["type"].value_counts()/comp_test_data_task2.shape[0]
print("distribution in gold competition test data")
print(type_distribution.reindex(type_list))

task2
distribution in own train data
type
compliment               0.175466
positive feedback        0.532418
affection declaration    0.172805
encouragement            0.047752
implicit                 0.012043
agreement                0.014564
ambiguous                0.013373
group membership         0.010223
sympathy                 0.006442
gratitude                0.014914
Name: count, dtype: float64
distribution in own test data
type
compliment               0.176005
positive feedback        0.535926
affection declaration    0.166117
encouragement            0.057350
implicit                 0.007251
agreement                0.010547
ambiguous                0.014502
group membership         0.013843
sympathy                 0.003296
gratitude                0.015162
Name: count, dtype: float64
distribution in gold competition test data
type
compliment               0.122118
positive feedback        0.498831
affection declaration    0.202639
encouragement            0.040094
implicit                 0.012028
agreement                0.007518
ambiguous                0.011026
group membership         0.065319
sympathy                 0.000668
gratitude                0.039759
Name: count, dtype: float64

In [140]:
print("spans per comment in own train data", own_train_data_task2.shape[0]/own_train_data_task1.shape[0])
print("spans per comment in own test data", own_test_data_task2.shape[0]/own_test_data_task1.shape[0])
print("spans per comment in gold competition test data", comp_test_data_task2.shape[0]/comp_test_data_task1.shape[0])

spans per comment in own train data 0.42823303649065997
spans per comment in own test data 0.4093362115488397
spans per comment in gold competition test data 0.6486076497995449

In [141]:
own_train_data_task2.head(3)

,document,comment_id,type,start,end,comment,flausch,translated,spelling_corrected,sentiment_orig,...,sentiment_translated,sentiment_anger,sentiment_disgust,sentiment_fear,sentiment_joy,sentiment_neutral,sentiment_sadness,sentiment_surprise,span,id
0,NDY-003,1,compliment,0,11,Respekt : o zu mir passt das heut vollkommen :...,yes,Respect : o to me this fits perfectly today :(...,Respekt - ob zu mir passt das heute vollkommen...,0.0,...,0.137500,0.317590,0.117705,0.004799,0.272843,0.234663,0.040224,0.012175,Respekt : o,NDY-003_1
1,NDY-003,1,compliment,48,71,Respekt : o zu mir passt das heut vollkommen :...,yes,Respect : o to me this fits perfectly today :(...,Respekt - ob zu mir passt das heute vollkommen...,0.0,...,0.137500,0.317590,0.117705,0.004799,0.272843,0.234663,0.040224,0.012175,Aber Respekt an euch ;),NDY-003_1
2,NDY-003,2,positive feedback,0,12,haha geil :D aber ich hab mich am anfang etwas...,yes,haha horny :D but I got a little scared at the...,Haha geil -Da aber ich hab mich am Anfang etwa...,0.7,...,0.503125,0.002527,0.001026,0.978153,0.002605,0.004189,0.009158,0.002342,haha geil :D,NDY-003_2

In [142]:
print("Average length of spans in own train data", (own_train_data_task2["end"] - own_train_data_task2["start"]).mean())
print("Average length of spans in own test data", (own_test_data_task2["end"] - own_test_data_task2["start"]).mean())
print("Average length of spans in gold competition test data", (comp_test_data_task2["end"] - comp_test_data_task2["start"]).mean())

Average length of spans in own train data 28.835807309900574
Average length of spans in own test data 28.137112722478577
Average length of spans in gold competition test data 26.303040427664552

# Evaluate Fine-Tuned models for subtask 2

## Wiebke/flausch_span_gbert-large_all

In [192]:
checkpoint = "Wiebke/flausch_span_gbert-large_all"
pipe = pipeline("token-classification", model=checkpoint)

Device set to use cuda:0

### own test

In [193]:
own_test_task2_dataset = Dataset.from_pandas(own_test_data_task2)

In [194]:
prediction_dataset = own_test_task2_dataset.map(
    apply_task2_pipeline,
    batched=True,
    batch_size=16,
    num_proc=1,
    fn_kwargs={"pipeline": pipe, "column": "comment"}
)

Map:   0%|          | 0/1517 [00:00<?, ? examples/s]

In [195]:
df = pd.DataFrame(prediction_dataset)
out_task2 = output_task2(df)
gold_data_task2 = own_test_data_task2[["document", "comment_id", "type", "start","end"]]

In [196]:
results = on_data_fine_grained_flausch_by_label(gold_data_task2, out_task2)

STRICT:
  0.29871977240398295 0.6921555702043507 0.417329093799682
SPANS:
  0.31493598862019917 0.7297297297297297 0.4399841017488077
TYPES:
  0.37724039829302985 0.8740936058009229 0.527027027027027

In [197]:

typeList = gold_data_task2["type"].unique()
all = []
for t in typeList:
    print(t)
    print(pd.DataFrame(results[t]))
    print()

positive feedback
        STRICT     TYPES
prec  0.741016  0.950637
rec   0.735547  0.900452
f1    0.738272  0.924864

affection declaration
        STRICT     TYPES
prec  0.627660  0.904110
rec   0.702381  0.868421
f1    0.662921  0.885906

group membership
        STRICT     TYPES
prec  0.470588  0.866667
rec   0.380952  0.722222
f1    0.421053  0.787879

encouragement
        STRICT     TYPES
prec  0.589474  0.945946
rec   0.643678  0.843373
f1    0.615385  0.891720

compliment
        STRICT     TYPES
prec  0.560976  0.890295
rec   0.689139  0.890295
f1    0.618487  0.890295

ambiguous
        STRICT     TYPES
prec  0.750000  0.916667
rec   0.409091  0.500000
f1    0.529412  0.647059

implicit
        STRICT     TYPES
prec  0.500000  1.000000
rec   0.090909  0.181818
f1    0.153846  0.307692

sympathy
      STRICT     TYPES
prec     0.0  0.333333
rec      0.0  0.200000
f1       0.0  0.250000

agreement
        STRICT     TYPES
prec  0.500000  1.000000
rec   0.062500  0.125000
f1    0.111111  0.222222

gratitude
        STRICT     TYPES
prec  0.800000  1.000000
rec   0.695652  0.818182
f1    0.744186  0.900000

### competition test

In [198]:
comp_test_comment_dataset = Dataset.from_pandas(comp_test_comment)

In [199]:
prediction_dataset = comp_test_comment_dataset.map(
    apply_task2_pipeline,
    batched=True,
    batch_size=16,
    num_proc=1,
    fn_kwargs={"pipeline": pipe, "column": "comment"}
)

Map:   0%|          | 0/9229 [00:00<?, ? examples/s]

In [200]:
df = pd.DataFrame(prediction_dataset)
out_task2 = output_task2(df)
gold_data_task2 = comp_test_data_task2[["document", "comment_id", "type", "start","end"]]

In [201]:
results = on_data_fine_grained_flausch_by_label(gold_data_task2, out_task2)

STRICT:
  0.5394585726004922 0.5492816572001337 0.544325800844301
SPANS:
  0.5737489745693191 0.5841964584029402 0.5789255856303287
TYPES:
  0.7286300246103363 0.7418977614433678 0.7352040394007118

In [202]:

typeList = gold_data_task2["type"].unique()
all = []
for t in typeList:
    print(t)
    print(pd.DataFrame(results[t]))
    print()

compliment
       STRICT     TYPES
prec  0.39090  0.731469
rec   0.51710  0.815913
f1    0.44523  0.771386

affection declaration
        STRICT     TYPES
prec  0.599096  0.868472
rec   0.655400  0.862632
f1    0.625984  0.865542

positive feedback
        STRICT     TYPES
prec  0.581090  0.857513
rec   0.592766  0.809951
f1    0.586870  0.833054

implicit
      STRICT     TYPES
prec     0.0  0.666667
rec      0.0  0.027778
f1       0.0  0.053333

ambiguous
        STRICT     TYPES
prec  0.430556  0.478261
rec   0.469697  0.500000
f1    0.449275  0.488889

encouragement
        STRICT     TYPES
prec  0.550000  0.795181
rec   0.641667  0.838983
f1    0.592308  0.816495

group membership
        STRICT     TYPES
prec  0.211864  0.782178
rec   0.063939  0.273356
f1    0.098232  0.405128

agreement
        STRICT     TYPES
prec  0.176471  0.470588
rec   0.066667  0.181818
f1    0.096774  0.262295

gratitude
        STRICT     TYPES
prec  0.507692  0.856459
rec   0.554622  0.821101
f1    0.530120  0.838407

sympathy
      STRICT  TYPES
prec     0.0    0.0
rec      0.0    0.0
f1       0.0    0.0

## Wiebke/flausch_span_gbert-large_non_labeled_spans

In [203]:
checkpoint = "Wiebke/flausch_span_gbert-large_non_labeled_spans"
pipe = pipeline("token-classification", model=checkpoint)

Device set to use cuda:0

### own test

In [204]:
own_test_task2_dataset = Dataset.from_pandas(own_test_data_task2)

In [205]:
prediction_dataset = own_test_task2_dataset.map(
    apply_task2_pipeline,
    batched=True,
    batch_size=16,
    num_proc=1,
    fn_kwargs={"pipeline": pipe, "column": "comment"}
)

Map:   0%|          | 0/1517 [00:00<?, ? examples/s]

In [206]:
df = pd.DataFrame(prediction_dataset)
out_task2 = output_task2(df)
gold_data_task2 = own_test_data_task2[["document", "comment_id", "type", "start","end"]]
gold_data_task2["type"] = ["span" for i in range(gold_data_task2.shape[0])]

In [207]:
results = on_data_flausch_spans(gold_data_task2, out_task2)

STRICT:
  0.4010821778829895 0.7818061964403428 0.5301743406347788
SPANS:
  0.4010821778829895 0.7818061964403428 0.5301743406347788
TYPES:
  0.4842746026378086 0.9439683586025049 0.6401430487259723

### competition test

In [211]:
comp_test_comment_dataset = Dataset.from_pandas(comp_test_comment)

In [212]:
prediction_dataset = comp_test_comment_dataset.map(
    apply_task2_pipeline,
    batched=True,
    batch_size=16,
    num_proc=1,
    fn_kwargs={"pipeline": pipe, "column": "comment"}
)

Map:   0%|          | 0/9229 [00:00<?, ? examples/s]

In [216]:
df = pd.DataFrame(prediction_dataset)
out_task2 = output_task2(df)
out_task2["type"] = ["span" for i in range(out_task2.shape[0])]
gold_data_task2 = comp_test_data_task2[["document", "comment_id", "type", "start","end"]]
gold_data_task2["type"] = ["span" for i in range(gold_data_task2.shape[0])]

In [217]:
results = on_data_flausch_spans(gold_data_task2, out_task2)

STRICT:
  0.6838145231846019 0.6528566655529568 0.6679770959747029
SPANS:
  0.6838145231846019 0.6528566655529568 0.6679770959747029
TYPES:
  0.8589676290463693 0.8200801871032409 0.8390735834544056

## Wiebke/results_flausch_classification_gbert-large_span_classifier

In [218]:
checkpoint = "Wiebke/results_flausch_classification_gbert-large_span_classifier"
pipe = pipeline("text-classification", model=checkpoint)

Device set to use cuda:0

### own test

In [222]:
out_task2 = own_test_data_task2[["span","type"]].copy()
out_task2['type'] = out_task2.apply(lambda row: apply_span_classification_pipeline(row, pipe), axis=1)

In [225]:
gold_data_task2 = own_test_data_task2[["span","type"]].copy()

In [226]:
from sklearn.metrics import classification_report
print(classification_report(gold_data_task2["type"], out_task2["type"]))

                       precision    recall  f1-score   support

affection declaration       0.91      0.91      0.91       252
            agreement       0.94      0.94      0.94        16
            ambiguous       0.77      0.45      0.57        22
           compliment       0.88      0.91      0.90       267
        encouragement       0.93      0.91      0.92        87
            gratitude       1.00      0.87      0.93        23
     group membership       0.90      0.86      0.88        21
             implicit       0.36      0.36      0.36        11
    positive feedback       0.95      0.95      0.95       813
             sympathy       0.50      0.40      0.44         5

             accuracy                           0.92      1517
            macro avg       0.81      0.76      0.78      1517
         weighted avg       0.92      0.92      0.92      1517

### competition test

In [234]:
#
comp_test_data_task2 = comp_test_data_task2.merge(comp_test_comment, on= ["document", "comment_id"]).copy()
comp_test_data_task2["span"] = comp_test_data_task2.apply(lambda row: row["comment"][row["start"]:(row["end"]+1)], axis=1)

In [237]:
comp_test_task2_dataset = Dataset.from_pandas(comp_test_data_task2[["span","type"]])

In [238]:
out_task2 = comp_test_data_task2[["span","type"]].copy()
out_task2['type'] = out_task2.apply(lambda row: apply_span_classification_pipeline(row, pipe), axis=1)

In [239]:
gold_data_task2 = comp_test_data_task2[["span","type"]].copy()

In [240]:
print(classification_report(gold_data_task2["type"], out_task2["type"]))

                       precision    recall  f1-score   support

affection declaration       0.86      0.90      0.88      1213
            agreement       0.84      0.80      0.82        45
            ambiguous       0.62      0.61      0.61        66
           compliment       0.83      0.83      0.83       731
        encouragement       0.90      0.91      0.90       240
            gratitude       0.98      0.97      0.98       238
     group membership       0.69      0.57      0.63       391
             implicit       0.43      0.22      0.29        72
    positive feedback       0.91      0.93      0.92      2986
             sympathy       0.20      0.25      0.22         4

             accuracy                           0.88      5986
            macro avg       0.73      0.70      0.71      5986
         weighted avg       0.87      0.88      0.87      5986

## Wiebke/task2_flausch_classification_gbert-large_span_classifier_with_nonspan

In [247]:
checkpoint = "Wiebke/task2_flausch_classification_gbert-large_span_classifier_with_nonspan"
pipe = pipeline("text-classification", model=checkpoint)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

Device set to use cuda:0

### own test

In [248]:
own_test_data_task2_none = pd.read_csv(path + "phrases_with_labels_inlcuding_not_flausch_test.csv")
own_test_data_task2_none["label"].value_counts()

label
not                      6494
positive feedback         813
compliment                267
affection declaration     252
encouragement              87
gratitude                  23
ambiguous                  22
group membership           21
agreement                  16
implicit                   11
sympathy                    5
Name: count, dtype: int64

In [256]:
out_task2 = own_test_data_task2_none.copy()
out_task2 = out_task2.rename(columns={"phrase": "span"})

In [263]:
out_task2["span"] = out_task2["span"].apply(lambda x: str("") if x == "nan" else str(x))

In [264]:
out_task2['type'] = out_task2.apply(lambda row: apply_span_classification_pipeline(row, pipe), axis=1)

In [265]:
gold_data_task2 = out_task2[["span","label"]].copy()
gold_data_task2 = gold_data_task2.rename(columns={"label": "type"})

In [266]:
print(classification_report(gold_data_task2["type"], out_task2["type"]))

                       precision    recall  f1-score   support

affection declaration       0.83      0.87      0.85       252
            agreement       0.29      0.25      0.27        16
            ambiguous       0.46      0.27      0.34        22
           compliment       0.79      0.90      0.84       267
        encouragement       0.86      0.90      0.88        87
            gratitude       0.68      0.83      0.75        23
     group membership       0.76      0.76      0.76        21
             implicit       0.67      0.36      0.47        11
                  not       0.98      0.98      0.98      6494
    positive feedback       0.87      0.83      0.85       813
             sympathy       0.25      0.40      0.31         5

             accuracy                           0.95      8011
            macro avg       0.68      0.67      0.66      8011
         weighted avg       0.95      0.95      0.95      8011